import type { LvglImageColorFormat } from "./types";
import { DEFAULT_LVGL_INCLUDE } from "../codeGen/lvglInclude";

const AUTOGEN =
    "/* AUTO-GENERATED by EmbeddedFlow image converter — do not edit manually. */\n";

function lvglIncludeBlock(include: string): string {
    const inc = include || DEFAULT_LVGL_INCLUDE;
    if (inc === "lvgl.h") {
        return `#if defined(LV_LVGL_H_INCLUDE_SIMPLE)\n#include "lvgl.h"\n#else\n#include <lvgl.h>\n#endif`;
    }
    return `#include "${inc}"`;
}

function formatByteLine(bytes: number[], indent: string): string {
    const parts = bytes.map(b => `0x${b.toString(16).padStart(2, "0")}`);
    return `${indent}${parts.join(",")},`;
}

function formatDataArray(mapName: string, data: Buffer, bytesPerLine = 16): string[] {
    const lines: string[] = [
        `static const`,
        `LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST`,
        `uint8_t ${mapName}[] = {`
    ];
    const row: number[] = [];
    for (let i = 0; i < data.length; i++) {
        row.push(data[i]!);
        if (row.length >= bytesPerLine) {
            lines.push(formatByteLine(row, "    "));
            row.length = 0;
        }
    }
    if (row.length) {
        lines.push(formatByteLine(row, "    "));
    }
    lines.push("};", "");
    return lines;
}

/** Emit one `.c` file with map + `lv_image_dsc_t` (LVGL 9). */
export function generateLvgl9ImageSource(
    symbolName: string,
    width: number,
    height: number,
    stride: number,
    cf: LvglImageColorFormat,
    data: Buffer,
    lvglInclude?: string
): string {
    const mapName = `${symbolName}_map`;
    const attr = symbolName.toUpperCase().replace(/[^A-Z0-9]/g, "_");
    return [
        AUTOGEN,
        lvglIncludeBlock(lvglInclude ?? DEFAULT_LVGL_INCLUDE),
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
        `#ifndef LV_ATTRIBUTE_${attr}`,
        `#define LV_ATTRIBUTE_${attr}`,
        "#endif",
        "",
        ...formatDataArray(mapName, data),
        `const lv_image_dsc_t ${symbolName} = {`,
        "  .header = {",
        "    .magic = LV_IMAGE_HEADER_MAGIC,",
        `    .cf = ${cf},`,
        "    .flags = 0,",
        `    .w = ${width},`,
        `    .h = ${height},`,
        `    .stride = ${stride},`,
        "    .reserved_2 = 0,",
        "  },",
        `  .data_size = sizeof(${mapName}),`,
        `  .data = ${mapName},`,
        "  .reserved = NULL,",
        "};",
        ""
    ].join("\n");
}

/** Emit one `.c` file with map + `lv_img_dsc_t` (LVGL 8). */
export function generateLvgl8ImageSource(
    symbolName: string,
    width: number,
    height: number,
    cf: LvglImageColorFormat,
    data: Buffer,
    lvglInclude?: string
): string {
    const mapName = `${symbolName}_map`;
    const imgCf = lvgl8ImgCf(cf);
    const attr = symbolName.toUpperCase().replace(/[^A-Z0-9]/g, "_");
    return [
        AUTOGEN,
        lvglIncludeBlock(lvglInclude ?? DEFAULT_LVGL_INCLUDE),
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
        `#ifndef LV_ATTRIBUTE_${attr}`,
        `#define LV_ATTRIBUTE_${attr}`,
        "#endif",
        "",
        ...formatDataArray(mapName, data),
        `const lv_img_dsc_t ${symbolName} = {`,
        "  .header.cf = " + imgCf + ",",
        "  .header.always_zero = 0,",
        "  .header.reserved = 0,",
        `  .header.w = ${width},`,
        `  .header.h = ${height},`,
        `  .data_size = sizeof(${mapName}),`,
        `  .data = ${mapName},`,
        "};",
        ""
    ].join("\n");
}

function lvgl8ImgCf(cf: LvglImageColorFormat): string {
    switch (cf) {
        case "LV_COLOR_FORMAT_RGB565":
        case "LV_COLOR_FORMAT_RGB565A8":
            return "LV_IMG_CF_TRUE_COLOR";
        case "LV_COLOR_FORMAT_ARGB8888":
        case "LV_COLOR_FORMAT_AL88":
            return "LV_IMG_CF_TRUE_COLOR_ALPHA";
        case "LV_COLOR_FORMAT_RGB888":
            return "LV_IMG_CF_TRUE_COLOR";
        case "LV_COLOR_FORMAT_L8":
            return "LV_IMG_CF_L8";
        default:
            return "LV_IMG_CF_TRUE_COLOR_ALPHA";
    }
}

/** Extern declarations for converted image assets (embedded in `ui.h`). */
export function generateImageExternLines(
    symbols: { symbolName: string; lvglV9: boolean }[]
): string[] {
    const lines: string[] = ["/* Image assets (ui_img_*.c in this folder) */"];
    for (const { symbolName, lvglV9 } of symbols) {
        const type = lvglV9 ? "lv_image_dsc_t" : "lv_img_dsc_t";
        lines.push(`extern const ${type} ${symbolName};`);
    }
    return lines;
}

/** @deprecated Use {@link generateImageExternLines} embedded in `ui.h` instead. */
export function generateImagesHeader(
    symbols: { symbolName: string; lvglV9: boolean }[],
    lvglInclude?: string
): string {
    const inc = lvglInclude ?? DEFAULT_LVGL_INCLUDE;
    const lines = [
        AUTOGEN,
        "#ifndef UI_IMAGES_H",
        "#define UI_IMAGES_H",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        `#include "${inc}"`,
        "",
        ...generateImageExternLines(symbols),
        "",
        "#ifdef __cplusplus",
        "} /* extern \"C\" */",
        "#endif",
        "",
        "#endif /* UI_IMAGES_H */",
        ""
    ];
    return lines.join("\n");
}
