/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

/* clang-format off */
#if 1

#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

/* Color depth — matches project display.bitDepth (ARGB8888) */
#define LV_COLOR_DEPTH 32

/* Memory */
#define LV_USE_STDLIB_MALLOC  LV_STDLIB_BUILTIN
#define LV_MEM_SIZE           (256U * 1024U)

/* HAL */
#define LV_DEF_REFR_PERIOD  33
#define LV_DPI_DEF          120

/* OS */
#define LV_USE_OS   LV_OS_NONE

/* Rendering */
#define LV_USE_DRAW_SW  1

/* Widgets used in this project — enable as needed */
#define LV_USE_LABEL        1
#define LV_USE_BUTTON       1
#define LV_USE_IMAGE        1
#define LV_USE_ARC          1
#define LV_USE_BAR          1
#define LV_USE_SLIDER       1
#define LV_USE_SWITCH       1
#define LV_USE_CHECKBOX     1
#define LV_USE_SPINNER      1
#define LV_USE_DROPDOWN     1
#define LV_USE_ROLLER       1
#define LV_USE_TEXTAREA     1
#define LV_USE_LINE         1
#define LV_USE_BUTTONMATRIX 1

/* Fonts */
#define LV_FONT_MONTSERRAT_12  1
#define LV_FONT_MONTSERRAT_14  1
#define LV_FONT_MONTSERRAT_16  1
#define LV_FONT_MONTSERRAT_20  1
#define LV_FONT_MONTSERRAT_24  1
#define LV_FONT_MONTSERRAT_32  1
#define LV_FONT_MONTSERRAT_48  1
#define LV_FONT_DEFAULT        &lv_font_montserrat_14

/* Theme */
#define LV_USE_THEME_DEFAULT  1
#define LV_USE_FLEX           1
#define LV_USE_GRID           1

/* Bidirectional + Arabic/Persian shaping (project uses RTL locales) */
#define LV_USE_BIDI  1
#define LV_USE_ARABIC_PERSIAN_CHARS  1
#define LV_FONT_DEJAVU_16_PERSIAN_HEBREW  1
/* RTL / bidi (required when using ar/fa/he locales):
 *   #define LV_USE_BIDI  1
/* Required for joined Persian/Arabic letters (not just RTL order). */
 *   #define LV_USE_ARABIC_PERSIAN_CHARS  1
 */

#define LV_USE_LOG  0
#define LV_USE_ASSERT_NULL    1
#define LV_USE_ASSERT_MALLOC  1

/* Hide FPS / CPU overlay labels on the UI screen */
#define LV_USE_SYSMON         0
#define LV_USE_PERF_MONITOR   0
#define LV_USE_MEM_MONITOR    0

#endif /* LV_CONF_H */
#endif /* enable */
