/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#include "ui.h"

void ui_init(void)
{
    lv_theme_t *theme = lv_theme_default_init(
        lv_display_get_default(),
        lv_color_hex(0x2196F3),
        lv_color_hex(0x0D47A1),
        false,
        LV_FONT_DEFAULT
    );
    lv_display_set_theme(lv_display_get_default(), theme);

    /* Create all screens */
    ui_page_main_screen_init();

    /* Load initial screen */
    lv_screen_load(ui_page_main);
}
