/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#ifndef UI_H
#define UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_page_main.h"

/**
 * Initialise the UI: apply theme, create the first screen, load it.
 * Call once after lv_init() and your display driver initialisation.
 */
void ui_init(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* UI_H */
