/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#ifndef UI_DISPLAY_H
#define UI_DISPLAY_H

/**
 * Author JSON: width=1024, height=600, orientation=landscape
 * Use EMBF_DISPLAY_* when creating the LVGL display (same logical size as the VS Code preview).
 */
#define EMBF_DISPLAY_JSON_WIDTH  (1024U)
#define EMBF_DISPLAY_JSON_HEIGHT (600U)
#define EMBF_DISPLAY_HOR_RES     (1024U)
#define EMBF_DISPLAY_VER_RES     (600U)

#endif /* UI_DISPLAY_H */
