/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#include "ui_page_main.h"

/* Screen variable */
lv_obj_t *ui_page_main = NULL;

/* Widget variables */
lv_obj_t *ui_page_main_lbl_hello = NULL;

void ui_page_main_screen_init(void)
{
    ui_page_main = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_page_main, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_main, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *ui_page_main_lbl_hello = lv_label_create(ui_page_main);
    lv_label_set_text(ui_page_main_lbl_hello, "Hello, EmbeddedFlow!");
    lv_obj_set_pos(ui_page_main_lbl_hello, 10, 10);
    lv_obj_set_size(ui_page_main_lbl_hello, 600, 30);
    lv_obj_set_style_text_color(ui_page_main_lbl_hello, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_main_lbl_hello, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
