/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#ifndef UI_PAGE_MAIN_H
#define UI_PAGE_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

/** Screen object for page "Main" */
extern lv_obj_t *ui_page_main;

/* Widget objects */
extern lv_obj_t *ui_page_main_lbl_hello;

/** Create all widgets for the "Main" screen. */
void ui_page_main_screen_init(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* UI_PAGE_MAIN_H */
