/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#ifndef UI_PAGE_MAIN_H
#define UI_PAGE_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

/** Screen object for page "Page 3" */
extern lv_obj_t *ui_page_main;

/* Widget objects */
extern lv_obj_t *ui_page_main_sw_1;
extern lv_obj_t *ui_page_main_rol_1;
extern lv_obj_t *ui_page_main_ta_1;
extern lv_obj_t *ui_page_main_spin_1;
extern lv_obj_t *ui_page_main_knob_1;
extern lv_obj_t *ui_page_main_bar_1;
extern lv_obj_t *ui_page_main_sld_1;

/** Create all widgets for the "Page 3" screen. */
void ui_page_main_screen_init(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* UI_PAGE_MAIN_H */
