/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#ifndef UI_PAGE_STATION_H
#define UI_PAGE_STATION_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

/** Screen object for page "Station" */
extern lv_obj_t *ui_page_station;

/* Widget objects */
extern lv_obj_t *ui_page_station_cont_root;
extern lv_obj_t *ui_page_station_ln_header_sep;
extern lv_obj_t *ui_page_station_cont_main_left;
extern lv_obj_t *ui_page_station_lbl_temp_title;
extern lv_obj_t *ui_page_station_arc_temp_gauge;
extern lv_obj_t *ui_page_station_lbl_temp_value;
extern lv_obj_t *ui_page_station_lbl_temp_unit;
extern lv_obj_t *ui_page_station_lbl_temp_range;
extern lv_obj_t *ui_page_station_cont_temp_buttons;
extern lv_obj_t *ui_page_station_btn_cool_1;
extern lv_obj_t *ui_page_station_btn_mild_1;
extern lv_obj_t *ui_page_station_btn_hot_1;
extern lv_obj_t *ui_page_station_btn_reset_temp;
extern lv_obj_t *ui_page_station_btn_play_anim_hint;
extern lv_obj_t *ui_page_station_cont_main_right;
extern lv_obj_t *ui_page_station_lbl_hum_title;
extern lv_obj_t *ui_page_station_bar_hum;
extern lv_obj_t *ui_page_station_lbl_hum_value;
extern lv_obj_t *ui_page_station_lbl_hum_unit;
extern lv_obj_t *ui_page_station_lbl_hum_status;
extern lv_obj_t *ui_page_station_cont_hum_buttons;
extern lv_obj_t *ui_page_station_btn_hum_dry;
extern lv_obj_t *ui_page_station_btn_hum_comfort;
extern lv_obj_t *ui_page_station_btn_hum_humid;
extern lv_obj_t *ui_page_station_ln_trend;
extern lv_obj_t *ui_page_station_cont_footer;
extern lv_obj_t *ui_page_station_lbl_date;
extern lv_obj_t *ui_page_station_lbl_footer_hint;
extern lv_obj_t *ui_page_station_cont_header;
extern lv_obj_t *ui_page_station_lbl_app_title;
extern lv_obj_t *ui_page_station_btn_open_settings;
extern lv_obj_t *ui_page_station_lbl_clock;
extern lv_obj_t *ui_page_station_spn_refresh;
extern lv_obj_t *ui_page_station_sw_night;
extern lv_obj_t *ui_page_station_lbl_night;

/** Create all widgets for the "Station" screen. */
void ui_page_station_screen_init(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* UI_PAGE_STATION_H */
