/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

/* ui.h includes every ui_<page>.h so navigate handlers can reference other screens. */
#include "ui.h"

/* Screen variable */
lv_obj_t *ui_page_settings = NULL;

/* Widget variables */
lv_obj_t *ui_page_settings_cont_settings_root = NULL;
lv_obj_t *ui_page_settings_cont_settings_header = NULL;
lv_obj_t *ui_page_settings_lbl_settings_title = NULL;
lv_obj_t *ui_page_settings_lbl_settings_sub = NULL;
lv_obj_t *ui_page_settings_btn_back_station = NULL;
lv_obj_t *ui_page_settings_ln_settings_sep = NULL;
lv_obj_t *ui_page_settings_cont_settings_body = NULL;
lv_obj_t *ui_page_settings_lbl_language_title = NULL;
lv_obj_t *ui_page_settings_lbl_language_hint = NULL;
lv_obj_t *ui_page_settings_btn_lang_en = NULL;
lv_obj_t *ui_page_settings_btn_lang_de = NULL;
lv_obj_t *ui_page_settings_btn_lang_fa = NULL;
lv_obj_t *ui_page_settings_ln_settings_divider = NULL;
lv_obj_t *ui_page_settings_lbl_dark_mode = NULL;
lv_obj_t *ui_page_settings_sw_dark_theme = NULL;
lv_obj_t *ui_page_settings_lbl_brightness = NULL;
lv_obj_t *ui_page_settings_lbl_brightness_val = NULL;
lv_obj_t *ui_page_settings_slider_brightness = NULL;

/* Forward declarations */
static void ui_page_settings_btn_back_station_on_clicked(lv_event_t *e);
static void ui_page_settings_btn_lang_en_on_clicked(lv_event_t *e);
static void ui_page_settings_btn_lang_de_on_clicked(lv_event_t *e);
static void ui_page_settings_btn_lang_fa_on_clicked(lv_event_t *e);
static void ui_page_settings_sw_dark_theme_on_value_changed(lv_event_t *e);
static void ui_page_settings_on_swipe(lv_event_t *e);
static void ui_page_settings_select_group_0(lv_obj_t *active);

/* Static helpers */
static void ui_page_settings_select_group_0(lv_obj_t *active)
{
    if (active == NULL) {
        return;
    }
    if (ui_page_settings_btn_lang_en) {
        lv_obj_set_style_bg_color(ui_page_settings_btn_lang_en, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_en, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_page_settings_btn_lang_en, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_en, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_page_settings_btn_lang_en, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_page_settings_btn_lang_en, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_page_settings_btn_lang_en, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_page_settings_btn_lang_en, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (ui_page_settings_btn_lang_de) {
        lv_obj_set_style_bg_color(ui_page_settings_btn_lang_de, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_de, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_page_settings_btn_lang_de, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_de, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_page_settings_btn_lang_de, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_page_settings_btn_lang_de, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_page_settings_btn_lang_de, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_page_settings_btn_lang_de, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (ui_page_settings_btn_lang_fa) {
        lv_obj_set_style_bg_color(ui_page_settings_btn_lang_fa, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_fa, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_page_settings_btn_lang_fa, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_fa, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_page_settings_btn_lang_fa, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_page_settings_btn_lang_fa, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_page_settings_btn_lang_fa, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_page_settings_btn_lang_fa, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (active) {
        lv_obj_set_style_bg_color(active, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(active, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(active, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(active, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

/* Event callback implementations */
static void ui_page_settings_btn_back_station_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        lv_screen_load_anim(ui_page_station, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, false);
    }
}

static void ui_page_settings_btn_lang_en_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        { ui_set_locale("en"); }
        { ui_page_settings_select_group_0(ui_page_settings_btn_lang_en); }
    }
}

static void ui_page_settings_btn_lang_de_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        { ui_set_locale("de"); }
        { ui_page_settings_select_group_0(ui_page_settings_btn_lang_de); }
    }
}

static void ui_page_settings_btn_lang_fa_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        { ui_set_locale("fa"); }
        { ui_page_settings_select_group_0(ui_page_settings_btn_lang_fa); }
    }
}

static void ui_page_settings_sw_dark_theme_on_value_changed(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_VALUE_CHANGED) {
        { lv_theme_t *t = lv_theme_default_init(lv_display_get_default(), lv_color_hex(0x2DD4FF), lv_color_hex(0xA78BFA), lv_obj_has_state(lv_event_get_target_obj(e), LV_STATE_CHECKED), LV_FONT_DEFAULT); lv_display_set_theme(lv_display_get_default(), t); lv_obj_invalidate(lv_screen_active()); }
    }
}

static void ui_page_settings_on_swipe(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_GESTURE) {
        return;
    }
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_active());
    if (dir == LV_DIR_LEFT) {
        lv_screen_load(ui_page_main);
    }
}

void ui_page_settings_screen_init(void)
{
    ui_page_settings = lv_obj_create(NULL);
    lv_obj_set_style_base_dir(ui_page_settings, LV_BASE_DIR_LTR, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_page_settings, lv_color_hex(0x070A12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_cont_settings_root = lv_obj_create(ui_page_settings);
    lv_obj_set_style_pad_all(ui_page_settings_cont_settings_root, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_settings_cont_settings_root, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_settings_cont_settings_root, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_settings_cont_settings_root, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    ui_page_settings_cont_settings_header = lv_obj_create(ui_page_settings_cont_settings_root);
    lv_obj_set_style_pad_all(ui_page_settings_cont_settings_header, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_settings_cont_settings_header, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_settings_cont_settings_header, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_settings_cont_settings_header, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    ui_page_settings_lbl_settings_title = lv_label_create(ui_page_settings_cont_settings_header);
    lv_label_set_text(ui_page_settings_lbl_settings_title, ui_get_string(UI_STR_STRING_SETTINGS_TITLE));
    lv_obj_set_pos(ui_page_settings_lbl_settings_title, 14, 10);
    lv_obj_set_size(ui_page_settings_lbl_settings_title, 320, 32);
    lv_obj_set_style_text_color(ui_page_settings_lbl_settings_title, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_settings_lbl_settings_title, ui_font_montserrat_nearest(26), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_lbl_settings_sub = lv_label_create(ui_page_settings_cont_settings_header);
    lv_label_set_text(ui_page_settings_lbl_settings_sub, ui_get_string(UI_STR_STRING_SETTINGS_SUB));
    lv_obj_set_pos(ui_page_settings_lbl_settings_sub, 14, 38);
    lv_obj_set_size(ui_page_settings_lbl_settings_sub, 400, 22);
    lv_obj_set_style_text_color(ui_page_settings_lbl_settings_sub, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_settings_lbl_settings_sub, ui_font_montserrat_nearest(16), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_btn_back_station = lv_button_create(ui_page_settings_cont_settings_header);
    lv_obj_t *ui_page_settings_btn_back_station_lbl = lv_label_create(ui_page_settings_btn_back_station);
    lv_label_set_text(ui_page_settings_btn_back_station_lbl, ui_get_string(UI_STR_STRING_BACK));
    lv_obj_center(ui_page_settings_btn_back_station_lbl);
    lv_obj_set_style_text_font(ui_page_settings_btn_back_station_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_settings_btn_back_station, 820, 12);
    lv_obj_set_size(ui_page_settings_btn_back_station, 140, 40);
    lv_obj_set_style_bg_color(ui_page_settings_btn_back_station, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings_btn_back_station, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_settings_btn_back_station, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings_btn_back_station, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_settings_btn_back_station, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_settings_btn_back_station, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_settings_btn_back_station, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_settings_btn_back_station, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_pos(ui_page_settings_cont_settings_header, 24, 18);
    lv_obj_set_size(ui_page_settings_cont_settings_header, 976, 64);
    lv_obj_add_style(ui_page_settings_cont_settings_header, &ui_style_header_card, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_point_precise_t ui_page_settings_ln_settings_sep_points[] = {{24, 0}, {1000, 0}};
    ui_page_settings_ln_settings_sep = lv_line_create(ui_page_settings_cont_settings_root);
    lv_line_set_points(ui_page_settings_ln_settings_sep, ui_page_settings_ln_settings_sep_points, 2);
    lv_obj_set_pos(ui_page_settings_ln_settings_sep, 0, 92);
    lv_obj_set_size(ui_page_settings_ln_settings_sep, 1024, 6);

    ui_page_settings_cont_settings_body = lv_obj_create(ui_page_settings_cont_settings_root);
    lv_obj_set_style_pad_all(ui_page_settings_cont_settings_body, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_settings_cont_settings_body, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_settings_cont_settings_body, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_settings_cont_settings_body, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    ui_page_settings_lbl_language_title = lv_label_create(ui_page_settings_cont_settings_body);
    lv_label_set_text(ui_page_settings_lbl_language_title, ui_get_string(UI_STR_STRING_LANGUAGE));
    lv_obj_set_pos(ui_page_settings_lbl_language_title, 24, 24);
    lv_obj_set_size(ui_page_settings_lbl_language_title, 240, 28);
    lv_obj_set_style_text_color(ui_page_settings_lbl_language_title, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_settings_lbl_language_title, ui_font_montserrat_nearest(22), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_lbl_language_hint = lv_label_create(ui_page_settings_cont_settings_body);
    lv_label_set_text(ui_page_settings_lbl_language_hint, ui_get_string(UI_STR_STRING_LANGUAGE_HINT));
    lv_obj_set_pos(ui_page_settings_lbl_language_hint, 24, 54);
    lv_obj_set_size(ui_page_settings_lbl_language_hint, 520, 22);
    lv_obj_set_style_text_color(ui_page_settings_lbl_language_hint, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_settings_lbl_language_hint, ui_font_montserrat_nearest(16), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_btn_lang_en = lv_button_create(ui_page_settings_cont_settings_body);
    lv_obj_t *ui_page_settings_btn_lang_en_lbl = lv_label_create(ui_page_settings_btn_lang_en);
    lv_label_set_text(ui_page_settings_btn_lang_en_lbl, ui_get_string(UI_STR_STRING_ENGLISH));
    lv_obj_center(ui_page_settings_btn_lang_en_lbl);
    lv_obj_set_style_text_font(ui_page_settings_btn_lang_en_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_settings_btn_lang_en, 24, 92);
    lv_obj_set_size(ui_page_settings_btn_lang_en, 220, 44);
    lv_obj_set_style_bg_color(ui_page_settings_btn_lang_en, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_en, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_settings_btn_lang_en, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_settings_btn_lang_en, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_settings_btn_lang_en, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_settings_btn_lang_en, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_btn_lang_de = lv_button_create(ui_page_settings_cont_settings_body);
    lv_obj_t *ui_page_settings_btn_lang_de_lbl = lv_label_create(ui_page_settings_btn_lang_de);
    lv_label_set_text(ui_page_settings_btn_lang_de_lbl, ui_get_string(UI_STR_STRING_GERMAN));
    lv_obj_center(ui_page_settings_btn_lang_de_lbl);
    lv_obj_set_style_text_font(ui_page_settings_btn_lang_de_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_settings_btn_lang_de, 260, 92);
    lv_obj_set_size(ui_page_settings_btn_lang_de, 220, 44);
    lv_obj_set_style_bg_color(ui_page_settings_btn_lang_de, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_de, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_settings_btn_lang_de, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_de, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_settings_btn_lang_de, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_settings_btn_lang_de, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_settings_btn_lang_de, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_settings_btn_lang_de, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_btn_lang_fa = lv_button_create(ui_page_settings_cont_settings_body);
    lv_obj_t *ui_page_settings_btn_lang_fa_lbl = lv_label_create(ui_page_settings_btn_lang_fa);
    lv_label_set_text(ui_page_settings_btn_lang_fa_lbl, ui_get_string(UI_STR_STRING_PERSIAN));
    lv_obj_center(ui_page_settings_btn_lang_fa_lbl);
    lv_obj_set_style_text_font(ui_page_settings_btn_lang_fa_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_settings_btn_lang_fa, 496, 92);
    lv_obj_set_size(ui_page_settings_btn_lang_fa, 220, 44);
    lv_obj_set_style_bg_color(ui_page_settings_btn_lang_fa, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_fa, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_settings_btn_lang_fa, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings_btn_lang_fa, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_settings_btn_lang_fa, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_settings_btn_lang_fa, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_settings_btn_lang_fa, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_settings_btn_lang_fa, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_point_precise_t ui_page_settings_ln_settings_divider_points[] = {{0, 0}, {928, 0}};
    ui_page_settings_ln_settings_divider = lv_line_create(ui_page_settings_cont_settings_body);
    lv_line_set_points(ui_page_settings_ln_settings_divider, ui_page_settings_ln_settings_divider_points, 2);
    lv_obj_set_pos(ui_page_settings_ln_settings_divider, 24, 168);
    lv_obj_set_size(ui_page_settings_ln_settings_divider, 928, 2);

    ui_page_settings_lbl_dark_mode = lv_label_create(ui_page_settings_cont_settings_body);
    lv_label_set_text(ui_page_settings_lbl_dark_mode, "Dark theme");
    lv_obj_set_pos(ui_page_settings_lbl_dark_mode, 24, 196);
    lv_obj_set_size(ui_page_settings_lbl_dark_mode, 240, 28);
    lv_obj_add_style(ui_page_settings_lbl_dark_mode, &ui_style_muted_text, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_settings_lbl_dark_mode, ui_font_montserrat_nearest(18), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_sw_dark_theme = lv_switch_create(ui_page_settings_cont_settings_body);
    lv_obj_add_state(ui_page_settings_sw_dark_theme, LV_STATE_CHECKED);
    lv_obj_set_pos(ui_page_settings_sw_dark_theme, 896, 194);
    lv_obj_set_size(ui_page_settings_sw_dark_theme, 56, 32);

    ui_page_settings_lbl_brightness = lv_label_create(ui_page_settings_cont_settings_body);
    lv_label_set_text(ui_page_settings_lbl_brightness, "Screen brightness");
    lv_obj_set_pos(ui_page_settings_lbl_brightness, 24, 252);
    lv_obj_set_size(ui_page_settings_lbl_brightness, 240, 28);
    lv_obj_add_style(ui_page_settings_lbl_brightness, &ui_style_muted_text, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_settings_lbl_brightness, ui_font_montserrat_nearest(18), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_lbl_brightness_val = lv_label_create(ui_page_settings_cont_settings_body);
    lv_label_set_text(ui_page_settings_lbl_brightness_val, "72%");
    lv_obj_set_pos(ui_page_settings_lbl_brightness_val, 864, 252);
    lv_obj_set_size(ui_page_settings_lbl_brightness_val, 88, 28);
    lv_obj_set_style_text_color(ui_page_settings_lbl_brightness_val, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_settings_lbl_brightness_val, ui_font_montserrat_nearest(18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_settings_lbl_brightness_val, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_settings_slider_brightness = lv_slider_create(ui_page_settings_cont_settings_body);
    lv_slider_set_range(ui_page_settings_slider_brightness, 10, 100);
    lv_slider_set_value(ui_page_settings_slider_brightness, 72, LV_ANIM_OFF);
    lv_obj_set_pos(ui_page_settings_slider_brightness, 24, 288);
    lv_obj_set_size(ui_page_settings_slider_brightness, 928, 32);
    lv_obj_set_style_bg_color(ui_page_settings_slider_brightness, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings_slider_brightness, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_settings_slider_brightness, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_settings_slider_brightness, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_pos(ui_page_settings_cont_settings_body, 24, 110);
    lv_obj_set_size(ui_page_settings_cont_settings_body, 976, 470);
    lv_obj_add_style(ui_page_settings_cont_settings_body, &ui_style_metric_card, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_pos(ui_page_settings_cont_settings_root, 0, 0);
    lv_obj_set_size(ui_page_settings_cont_settings_root, 1024, 600);
    lv_obj_add_style(ui_page_settings_cont_settings_root, &ui_style_app_bg, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Event registrations */
    lv_obj_add_event_cb(ui_page_settings_btn_back_station, ui_page_settings_btn_back_station_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_settings_btn_lang_en, ui_page_settings_btn_lang_en_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_settings_btn_lang_de, ui_page_settings_btn_lang_de_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_settings_btn_lang_fa, ui_page_settings_btn_lang_fa_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_settings_sw_dark_theme, ui_page_settings_sw_dark_theme_on_value_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_page_settings, ui_page_settings_on_swipe, LV_EVENT_GESTURE, NULL);
    /* Exclusive button groups — design default */
    ui_page_settings_select_group_0(ui_page_settings_btn_lang_en);

}
