/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

/* ui.h includes every ui_<page>.h so navigate handlers can reference other screens. */
#include "ui.h"

/* Screen variable */
lv_obj_t *ui_page_station = NULL;

/* Widget variables */
lv_obj_t *ui_page_station_cont_root = NULL;
lv_obj_t *ui_page_station_ln_header_sep = NULL;
lv_obj_t *ui_page_station_cont_main_left = NULL;
lv_obj_t *ui_page_station_lbl_temp_title = NULL;
lv_obj_t *ui_page_station_arc_temp_gauge = NULL;
lv_obj_t *ui_page_station_lbl_temp_value = NULL;
lv_obj_t *ui_page_station_lbl_temp_unit = NULL;
lv_obj_t *ui_page_station_lbl_temp_range = NULL;
lv_obj_t *ui_page_station_cont_temp_buttons = NULL;
lv_obj_t *ui_page_station_btn_cool_1 = NULL;
lv_obj_t *ui_page_station_btn_mild_1 = NULL;
lv_obj_t *ui_page_station_btn_hot_1 = NULL;
lv_obj_t *ui_page_station_btn_reset_temp = NULL;
lv_obj_t *ui_page_station_btn_play_anim_hint = NULL;
lv_obj_t *ui_page_station_cont_main_right = NULL;
lv_obj_t *ui_page_station_lbl_hum_title = NULL;
lv_obj_t *ui_page_station_bar_hum = NULL;
lv_obj_t *ui_page_station_lbl_hum_value = NULL;
lv_obj_t *ui_page_station_lbl_hum_unit = NULL;
lv_obj_t *ui_page_station_lbl_hum_status = NULL;
lv_obj_t *ui_page_station_cont_hum_buttons = NULL;
lv_obj_t *ui_page_station_btn_hum_dry = NULL;
lv_obj_t *ui_page_station_btn_hum_comfort = NULL;
lv_obj_t *ui_page_station_btn_hum_humid = NULL;
lv_obj_t *ui_page_station_ln_trend = NULL;
lv_obj_t *ui_page_station_cont_footer = NULL;
lv_obj_t *ui_page_station_lbl_date = NULL;
lv_obj_t *ui_page_station_lbl_footer_hint = NULL;
lv_obj_t *ui_page_station_cont_header = NULL;
lv_obj_t *ui_page_station_lbl_app_title = NULL;
lv_obj_t *ui_page_station_btn_open_settings = NULL;
lv_obj_t *ui_page_station_lbl_clock = NULL;
lv_obj_t *ui_page_station_spn_refresh = NULL;
lv_obj_t *ui_page_station_sw_night = NULL;
lv_obj_t *ui_page_station_lbl_night = NULL;

/* Forward declarations */
static void ui_page_station_btn_cool_1_on_clicked(lv_event_t *e);
static void ui_page_station_btn_mild_1_on_clicked(lv_event_t *e);
static void ui_page_station_btn_hot_1_on_clicked(lv_event_t *e);
static void ui_page_station_btn_reset_temp_on_clicked(lv_event_t *e);
static void ui_page_station_btn_play_anim_hint_on_clicked(lv_event_t *e);
static void ui_page_station_btn_hum_dry_on_clicked(lv_event_t *e);
static void ui_page_station_btn_hum_comfort_on_clicked(lv_event_t *e);
static void ui_page_station_btn_hum_humid_on_clicked(lv_event_t *e);
static void ui_page_station_btn_open_settings_on_clicked(lv_event_t *e);
static void ui_page_station_sw_night_on_value_changed(lv_event_t *e);
static void ui_page_station_on_swipe(lv_event_t *e);
static void ui_anim_opa_cb(void *obj, int32_t v);
static void ui_page_station_select_group_0(lv_obj_t *active);
static void ui_page_station_select_group_1(lv_obj_t *active);
static void ui_page_station_play_animations(void);

/* Static helpers */
static void ui_anim_opa_cb(void *obj, int32_t v)
{
    lv_obj_set_style_opa((lv_obj_t *)obj, (lv_opa_t)v, LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void ui_page_station_select_group_0(lv_obj_t *active)
{
    if (active == NULL) {
        return;
    }
    if (ui_page_station_btn_cool_1) {
        lv_obj_set_style_bg_color(ui_page_station_btn_cool_1, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_cool_1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_page_station_btn_cool_1, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_cool_1, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_page_station_btn_cool_1, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_page_station_btn_cool_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_page_station_btn_cool_1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_page_station_btn_cool_1, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (ui_page_station_btn_mild_1) {
        lv_obj_set_style_bg_color(ui_page_station_btn_mild_1, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_mild_1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_page_station_btn_mild_1, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_mild_1, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_page_station_btn_mild_1, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_page_station_btn_mild_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_page_station_btn_mild_1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_page_station_btn_mild_1, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (ui_page_station_btn_hot_1) {
        lv_obj_set_style_bg_color(ui_page_station_btn_hot_1, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_hot_1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_page_station_btn_hot_1, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_hot_1, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_page_station_btn_hot_1, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_page_station_btn_hot_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_page_station_btn_hot_1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_page_station_btn_hot_1, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (active) {
        lv_obj_set_style_bg_color(active, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(active, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(active, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(active, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

static void ui_page_station_select_group_1(lv_obj_t *active)
{
    if (active == NULL) {
        return;
    }
    if (ui_page_station_btn_hum_dry) {
        lv_obj_set_style_bg_color(ui_page_station_btn_hum_dry, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_hum_dry, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_page_station_btn_hum_dry, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_hum_dry, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_page_station_btn_hum_dry, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_page_station_btn_hum_dry, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_page_station_btn_hum_dry, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_page_station_btn_hum_dry, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (ui_page_station_btn_hum_comfort) {
        lv_obj_set_style_bg_color(ui_page_station_btn_hum_comfort, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_hum_comfort, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_page_station_btn_hum_comfort, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_hum_comfort, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_page_station_btn_hum_comfort, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_page_station_btn_hum_comfort, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_page_station_btn_hum_comfort, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_page_station_btn_hum_comfort, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (ui_page_station_btn_hum_humid) {
        lv_obj_set_style_bg_color(ui_page_station_btn_hum_humid, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_hum_humid, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_page_station_btn_hum_humid, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_page_station_btn_hum_humid, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_page_station_btn_hum_humid, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_page_station_btn_hum_humid, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_page_station_btn_hum_humid, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_page_station_btn_hum_humid, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (active) {
        lv_obj_set_style_bg_color(active, lv_color_hex(0xA78BFA), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(active, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(active, lv_color_hex(0xA78BFA), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(active, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

static void ui_page_station_play_animations(void)
{
    {
        lv_anim_t a_ui_page_station_arc_temp_gauge_0;
        lv_anim_init(&a_ui_page_station_arc_temp_gauge_0);
        lv_anim_set_var(&a_ui_page_station_arc_temp_gauge_0, ui_page_station_arc_temp_gauge);
        lv_anim_set_exec_cb(&a_ui_page_station_arc_temp_gauge_0, (lv_anim_exec_xcb_t)ui_anim_opa_cb);
        lv_anim_set_values(&a_ui_page_station_arc_temp_gauge_0, 180, 255);
        lv_anim_set_time(&a_ui_page_station_arc_temp_gauge_0, 900);
        lv_anim_set_path_cb(&a_ui_page_station_arc_temp_gauge_0, lv_anim_path_ease_in_out);
        lv_anim_set_repeat_count(&a_ui_page_station_arc_temp_gauge_0, LV_ANIM_REPEAT_INFINITE);
        lv_anim_start(&a_ui_page_station_arc_temp_gauge_0);
    }
    {
        lv_anim_t a_ui_page_station_bar_hum_0;
        lv_anim_init(&a_ui_page_station_bar_hum_0);
        lv_anim_set_var(&a_ui_page_station_bar_hum_0, ui_page_station_bar_hum);
        lv_anim_set_exec_cb(&a_ui_page_station_bar_hum_0, (lv_anim_exec_xcb_t)ui_anim_opa_cb);
        lv_anim_set_values(&a_ui_page_station_bar_hum_0, 180, 255);
        lv_anim_set_time(&a_ui_page_station_bar_hum_0, 900);
        lv_anim_set_path_cb(&a_ui_page_station_bar_hum_0, lv_anim_path_ease_in_out);
        lv_anim_set_repeat_count(&a_ui_page_station_bar_hum_0, LV_ANIM_REPEAT_INFINITE);
        lv_anim_start(&a_ui_page_station_bar_hum_0);
    }
    {
        lv_anim_t a_ui_page_station_lbl_clock_0;
        lv_anim_init(&a_ui_page_station_lbl_clock_0);
        lv_anim_set_var(&a_ui_page_station_lbl_clock_0, ui_page_station_lbl_clock);
        lv_anim_set_exec_cb(&a_ui_page_station_lbl_clock_0, (lv_anim_exec_xcb_t)ui_anim_opa_cb);
        lv_anim_set_values(&a_ui_page_station_lbl_clock_0, 180, 255);
        lv_anim_set_time(&a_ui_page_station_lbl_clock_0, 700);
        lv_anim_set_path_cb(&a_ui_page_station_lbl_clock_0, lv_anim_path_ease_in_out);
        lv_anim_set_repeat_count(&a_ui_page_station_lbl_clock_0, LV_ANIM_REPEAT_INFINITE);
        lv_anim_start(&a_ui_page_station_lbl_clock_0);
    }
}

/* Event callback implementations */
static void ui_page_station_btn_cool_1_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        lv_arc_set_value(ui_page_station_arc_temp_gauge, 20);
        lv_label_set_text(ui_page_station_lbl_temp_value, "20");
        { ui_page_station_select_group_0(ui_page_station_btn_cool_1); }
    }
}

static void ui_page_station_btn_mild_1_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        lv_arc_set_value(ui_page_station_arc_temp_gauge, 24);
        lv_label_set_text(ui_page_station_lbl_temp_value, "24");
        { ui_page_station_select_group_0(ui_page_station_btn_mild_1); }
    }
}

static void ui_page_station_btn_hot_1_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        lv_arc_set_value(ui_page_station_arc_temp_gauge, 30);
        lv_label_set_text(ui_page_station_lbl_temp_value, "30");
        { ui_page_station_select_group_0(ui_page_station_btn_hot_1); }
    }
}

static void ui_page_station_btn_reset_temp_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        lv_arc_set_value(ui_page_station_arc_temp_gauge, 24);
        lv_label_set_text(ui_page_station_lbl_temp_value, "24");
    }
}

static void ui_page_station_btn_play_anim_hint_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        { ui_page_station_play_animations(); }
    }
}

static void ui_page_station_btn_hum_dry_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        lv_bar_set_value(ui_page_station_bar_hum, 35, LV_ANIM_OFF);
        lv_label_set_text(ui_page_station_lbl_hum_value, "35");
        lv_label_set_text(ui_page_station_lbl_hum_status, ui_get_string(UI_STR_STRING_DRY));
        { ui_page_station_select_group_1(ui_page_station_btn_hum_dry); }
    }
}

static void ui_page_station_btn_hum_comfort_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        lv_bar_set_value(ui_page_station_bar_hum, 56, LV_ANIM_OFF);
        lv_label_set_text(ui_page_station_lbl_hum_value, "56");
        lv_label_set_text(ui_page_station_lbl_hum_status, ui_get_string(UI_STR_STRING_COMFORT));
        { ui_page_station_select_group_1(ui_page_station_btn_hum_comfort); }
    }
}

static void ui_page_station_btn_hum_humid_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        lv_bar_set_value(ui_page_station_bar_hum, 78, LV_ANIM_OFF);
        lv_label_set_text(ui_page_station_lbl_hum_value, "78");
        lv_label_set_text(ui_page_station_lbl_hum_status, ui_get_string(UI_STR_STRING_HUMID));
        { ui_page_station_select_group_1(ui_page_station_btn_hum_humid); }
    }
}

static void ui_page_station_btn_open_settings_on_clicked(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        lv_screen_load_anim(ui_page_settings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, false);
    }
}

static void ui_page_station_sw_night_on_value_changed(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_VALUE_CHANGED) {
        { lv_theme_t *t = lv_theme_default_init(lv_display_get_default(), lv_color_hex(0x2DD4FF), lv_color_hex(0xA78BFA), lv_obj_has_state(lv_event_get_target_obj(e), LV_STATE_CHECKED), LV_FONT_DEFAULT); lv_display_set_theme(lv_display_get_default(), t); lv_obj_invalidate(lv_screen_active()); }
    }
}

static void ui_page_station_on_swipe(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_GESTURE) {
        return;
    }
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_active());
    if (dir == LV_DIR_TOP) {
        lv_screen_load_anim(ui_page_main, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0, false);
    }
}

void ui_page_station_screen_init(void)
{
    ui_page_station = lv_obj_create(NULL);
    lv_obj_set_style_base_dir(ui_page_station, LV_BASE_DIR_LTR, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_page_station, lv_color_hex(0x070A12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_page_station, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scroll_dir(ui_page_station, LV_DIR_NONE);

    ui_page_station_cont_root = lv_obj_create(ui_page_station);
    lv_obj_set_style_pad_all(ui_page_station_cont_root, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_station_cont_root, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_station_cont_root, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_station_cont_root, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    static lv_point_precise_t ui_page_station_ln_header_sep_points[] = {{24, 0}, {1000, 0}};
    ui_page_station_ln_header_sep = lv_line_create(ui_page_station_cont_root);
    lv_line_set_points(ui_page_station_ln_header_sep, ui_page_station_ln_header_sep_points, 2);
    lv_line_set_y_invert(ui_page_station_ln_header_sep, false);
    lv_obj_set_pos(ui_page_station_ln_header_sep, 0, 92);
    lv_obj_set_size(ui_page_station_ln_header_sep, 1024, 6);

    ui_page_station_cont_main_left = lv_obj_create(ui_page_station_cont_root);
    lv_obj_set_style_pad_all(ui_page_station_cont_main_left, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_station_cont_main_left, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_station_cont_main_left, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_station_cont_main_left, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    ui_page_station_lbl_temp_title = lv_label_create(ui_page_station_cont_main_left);
    lv_label_set_text(ui_page_station_lbl_temp_title, ui_get_string(UI_STR_STRING_TEMPERATURE));
    lv_obj_set_pos(ui_page_station_lbl_temp_title, 18, 10);
    lv_obj_set_size(ui_page_station_lbl_temp_title, 250, 26);
    lv_obj_set_style_text_color(ui_page_station_lbl_temp_title, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_temp_title, ui_font_montserrat_nearest(22), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_arc_temp_gauge = lv_arc_create(ui_page_station_cont_main_left);
    lv_arc_set_range(ui_page_station_arc_temp_gauge, -10, 50);
    lv_arc_set_value(ui_page_station_arc_temp_gauge, 24);
    lv_arc_set_bg_angles(ui_page_station_arc_temp_gauge, 220, 20);
    lv_obj_set_pos(ui_page_station_arc_temp_gauge, 52, 46);
    lv_obj_set_size(ui_page_station_arc_temp_gauge, 372, 192);
    lv_obj_set_style_bg_color(ui_page_station_arc_temp_gauge, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_arc_temp_gauge, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_arc_temp_gauge, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_arc_temp_gauge, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_arc_temp_gauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_arc_temp_gauge, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_anim_t a_ui_page_station_arc_temp_gauge_0;
        lv_anim_init(&a_ui_page_station_arc_temp_gauge_0);
        lv_anim_set_var(&a_ui_page_station_arc_temp_gauge_0, ui_page_station_arc_temp_gauge);
        lv_anim_set_exec_cb(&a_ui_page_station_arc_temp_gauge_0, (lv_anim_exec_xcb_t)ui_anim_opa_cb);
        lv_anim_set_values(&a_ui_page_station_arc_temp_gauge_0, 180, 255);
        lv_anim_set_time(&a_ui_page_station_arc_temp_gauge_0, 900);
        lv_anim_set_path_cb(&a_ui_page_station_arc_temp_gauge_0, lv_anim_path_ease_in_out);
        lv_anim_set_repeat_count(&a_ui_page_station_arc_temp_gauge_0, LV_ANIM_REPEAT_INFINITE);
        lv_anim_start(&a_ui_page_station_arc_temp_gauge_0);
    }

    ui_page_station_lbl_temp_value = lv_label_create(ui_page_station_cont_main_left);
    lv_label_set_text(ui_page_station_lbl_temp_value, "24");
    lv_obj_set_pos(ui_page_station_lbl_temp_value, 170, 132);
    lv_obj_set_size(ui_page_station_lbl_temp_value, 136, 70);
    lv_obj_set_style_text_color(ui_page_station_lbl_temp_value, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_temp_value, ui_font_montserrat_nearest(48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_temp_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_lbl_temp_unit = lv_label_create(ui_page_station_cont_main_left);
    lv_label_set_text(ui_page_station_lbl_temp_unit, "°C");
    lv_obj_set_pos(ui_page_station_lbl_temp_unit, 292, 204);
    lv_obj_set_size(ui_page_station_lbl_temp_unit, 80, 30);
    lv_obj_set_style_text_color(ui_page_station_lbl_temp_unit, lv_color_hex(0xA78BFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_temp_unit, ui_font_montserrat_nearest(28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_temp_unit, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_lbl_temp_range = lv_label_create(ui_page_station_cont_main_left);
    lv_label_set_text(ui_page_station_lbl_temp_range, ui_get_string(UI_STR_STRING_TEMP_RANGE));
    lv_obj_set_pos(ui_page_station_lbl_temp_range, 18, 222);
    lv_obj_set_size(ui_page_station_lbl_temp_range, 440, 26);
    lv_obj_set_style_text_color(ui_page_station_lbl_temp_range, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_temp_range, ui_font_montserrat_nearest(18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_temp_range, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_cont_temp_buttons = lv_obj_create(ui_page_station_cont_main_left);
    lv_obj_set_style_pad_all(ui_page_station_cont_temp_buttons, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_station_cont_temp_buttons, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_station_cont_temp_buttons, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_station_cont_temp_buttons, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    ui_page_station_btn_cool_1 = lv_button_create(ui_page_station_cont_temp_buttons);
    lv_obj_t *ui_page_station_btn_cool_1_lbl = lv_label_create(ui_page_station_btn_cool_1);
    lv_label_set_text(ui_page_station_btn_cool_1_lbl, ui_get_string(UI_STR_STRING_COOL));
    lv_obj_center(ui_page_station_btn_cool_1_lbl);
    lv_obj_set_style_text_font(ui_page_station_btn_cool_1_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_station_btn_cool_1, 0, 0);
    lv_obj_set_size(ui_page_station_btn_cool_1, 110, 36);
    lv_obj_set_style_bg_color(ui_page_station_btn_cool_1, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_cool_1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_btn_cool_1, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_cool_1, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_btn_cool_1, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_station_btn_cool_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_btn_cool_1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_btn_cool_1, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_btn_mild_1 = lv_button_create(ui_page_station_cont_temp_buttons);
    lv_obj_t *ui_page_station_btn_mild_1_lbl = lv_label_create(ui_page_station_btn_mild_1);
    lv_label_set_text(ui_page_station_btn_mild_1_lbl, ui_get_string(UI_STR_STRING_MILD));
    lv_obj_center(ui_page_station_btn_mild_1_lbl);
    lv_obj_set_style_text_font(ui_page_station_btn_mild_1_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_station_btn_mild_1, 116, 0);
    lv_obj_set_size(ui_page_station_btn_mild_1, 110, 36);
    lv_obj_set_style_bg_color(ui_page_station_btn_mild_1, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_mild_1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_btn_mild_1, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_mild_1, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_btn_mild_1, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_station_btn_mild_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_btn_mild_1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_btn_mild_1, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_btn_hot_1 = lv_button_create(ui_page_station_cont_temp_buttons);
    lv_obj_t *ui_page_station_btn_hot_1_lbl = lv_label_create(ui_page_station_btn_hot_1);
    lv_label_set_text(ui_page_station_btn_hot_1_lbl, ui_get_string(UI_STR_STRING_HOT));
    lv_obj_center(ui_page_station_btn_hot_1_lbl);
    lv_obj_set_style_text_font(ui_page_station_btn_hot_1_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_station_btn_hot_1, 232, 0);
    lv_obj_set_size(ui_page_station_btn_hot_1, 110, 36);
    lv_obj_set_style_bg_color(ui_page_station_btn_hot_1, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_hot_1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_btn_hot_1, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_hot_1, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_btn_hot_1, lv_color_hex(0x2DD4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_station_btn_hot_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_btn_hot_1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_btn_hot_1, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_btn_reset_temp = lv_button_create(ui_page_station_cont_temp_buttons);
    lv_obj_t *ui_page_station_btn_reset_temp_lbl = lv_label_create(ui_page_station_btn_reset_temp);
    lv_label_set_text(ui_page_station_btn_reset_temp_lbl, ui_get_string(UI_STR_STRING_RESET));
    lv_obj_center(ui_page_station_btn_reset_temp_lbl);
    lv_obj_set_style_text_font(ui_page_station_btn_reset_temp_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_station_btn_reset_temp, 0, 44);
    lv_obj_set_size(ui_page_station_btn_reset_temp, 220, 36);
    lv_obj_set_style_bg_color(ui_page_station_btn_reset_temp, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_reset_temp, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_btn_reset_temp, lv_color_hex(0x1F2A44), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_reset_temp, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_btn_reset_temp, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_station_btn_reset_temp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_btn_reset_temp, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_btn_reset_temp, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_btn_play_anim_hint = lv_button_create(ui_page_station_cont_temp_buttons);
    lv_obj_t *ui_page_station_btn_play_anim_hint_lbl = lv_label_create(ui_page_station_btn_play_anim_hint);
    lv_label_set_text(ui_page_station_btn_play_anim_hint_lbl, ui_get_string(UI_STR_STRING_PLAY_ANIMS));
    lv_obj_center(ui_page_station_btn_play_anim_hint_lbl);
    lv_obj_set_style_text_font(ui_page_station_btn_play_anim_hint_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_station_btn_play_anim_hint, 232, 44);
    lv_obj_set_size(ui_page_station_btn_play_anim_hint, 220, 36);
    lv_obj_set_style_bg_color(ui_page_station_btn_play_anim_hint, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_play_anim_hint, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_btn_play_anim_hint, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_play_anim_hint, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_btn_play_anim_hint, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_station_btn_play_anim_hint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_btn_play_anim_hint, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_btn_play_anim_hint, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_pos(ui_page_station_cont_temp_buttons, 18, 256);
    lv_obj_set_size(ui_page_station_cont_temp_buttons, 440, 86);

    lv_obj_set_pos(ui_page_station_cont_main_left, 24, 110);
    lv_obj_set_size(ui_page_station_cont_main_left, 476, 360);
    lv_obj_add_style(ui_page_station_cont_main_left, &ui_style_metric_card, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_cont_main_right = lv_obj_create(ui_page_station_cont_root);
    lv_obj_set_style_pad_all(ui_page_station_cont_main_right, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_station_cont_main_right, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_station_cont_main_right, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_station_cont_main_right, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    ui_page_station_lbl_hum_title = lv_label_create(ui_page_station_cont_main_right);
    lv_label_set_text(ui_page_station_lbl_hum_title, ui_get_string(UI_STR_STRING_HUMIDITY));
    lv_obj_set_pos(ui_page_station_lbl_hum_title, 18, 10);
    lv_obj_set_size(ui_page_station_lbl_hum_title, 250, 26);
    lv_obj_set_style_text_color(ui_page_station_lbl_hum_title, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_hum_title, ui_font_montserrat_nearest(22), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_bar_hum = lv_bar_create(ui_page_station_cont_main_right);
    lv_bar_set_range(ui_page_station_bar_hum, 0, 100);
    lv_bar_set_value(ui_page_station_bar_hum, 56, LV_ANIM_OFF);
    lv_obj_set_pos(ui_page_station_bar_hum, 18, 56);
    lv_obj_set_size(ui_page_station_bar_hum, 440, 28);
    lv_obj_set_style_bg_color(ui_page_station_bar_hum, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_bar_hum, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_bar_hum, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_bar_hum, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_bar_hum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_anim_t a_ui_page_station_bar_hum_0;
        lv_anim_init(&a_ui_page_station_bar_hum_0);
        lv_anim_set_var(&a_ui_page_station_bar_hum_0, ui_page_station_bar_hum);
        lv_anim_set_exec_cb(&a_ui_page_station_bar_hum_0, (lv_anim_exec_xcb_t)ui_anim_opa_cb);
        lv_anim_set_values(&a_ui_page_station_bar_hum_0, 180, 255);
        lv_anim_set_time(&a_ui_page_station_bar_hum_0, 900);
        lv_anim_set_path_cb(&a_ui_page_station_bar_hum_0, lv_anim_path_ease_in_out);
        lv_anim_set_repeat_count(&a_ui_page_station_bar_hum_0, LV_ANIM_REPEAT_INFINITE);
        lv_anim_start(&a_ui_page_station_bar_hum_0);
    }

    ui_page_station_lbl_hum_value = lv_label_create(ui_page_station_cont_main_right);
    lv_label_set_text(ui_page_station_lbl_hum_value, "56");
    lv_obj_set_pos(ui_page_station_lbl_hum_value, 18, 94);
    lv_obj_set_size(ui_page_station_lbl_hum_value, 200, 60);
    lv_obj_set_style_text_color(ui_page_station_lbl_hum_value, lv_color_hex(0xA78BFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_hum_value, ui_font_montserrat_nearest(48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_hum_value, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_lbl_hum_unit = lv_label_create(ui_page_station_cont_main_right);
    lv_label_set_text(ui_page_station_lbl_hum_unit, "%");
    lv_obj_set_pos(ui_page_station_lbl_hum_unit, 200, 108);
    lv_obj_set_size(ui_page_station_lbl_hum_unit, 120, 40);
    lv_obj_set_style_text_color(ui_page_station_lbl_hum_unit, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_hum_unit, ui_font_montserrat_nearest(30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_hum_unit, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_lbl_hum_status = lv_label_create(ui_page_station_cont_main_right);
    lv_label_set_text(ui_page_station_lbl_hum_status, ui_get_string(UI_STR_STRING_COMFORT));
    lv_obj_set_pos(ui_page_station_lbl_hum_status, 18, 152);
    lv_obj_set_size(ui_page_station_lbl_hum_status, 200, 42);
    lv_obj_add_style(ui_page_station_lbl_hum_status, &ui_style_chip, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_lbl_hum_status, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_hum_status, ui_font_montserrat_nearest(22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_hum_status, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_cont_hum_buttons = lv_obj_create(ui_page_station_cont_main_right);
    lv_obj_set_style_pad_all(ui_page_station_cont_hum_buttons, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_station_cont_hum_buttons, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_station_cont_hum_buttons, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_station_cont_hum_buttons, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    ui_page_station_btn_hum_dry = lv_button_create(ui_page_station_cont_hum_buttons);
    lv_obj_t *ui_page_station_btn_hum_dry_lbl = lv_label_create(ui_page_station_btn_hum_dry);
    lv_label_set_text(ui_page_station_btn_hum_dry_lbl, ui_get_string(UI_STR_STRING_DRY));
    lv_obj_center(ui_page_station_btn_hum_dry_lbl);
    lv_obj_set_style_text_font(ui_page_station_btn_hum_dry_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_station_btn_hum_dry, 0, 52);
    lv_obj_set_size(ui_page_station_btn_hum_dry, 132, 36);
    lv_obj_set_style_bg_color(ui_page_station_btn_hum_dry, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_hum_dry, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_btn_hum_dry, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_hum_dry, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_btn_hum_dry, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_station_btn_hum_dry, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_btn_hum_dry, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_btn_hum_dry, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_btn_hum_comfort = lv_button_create(ui_page_station_cont_hum_buttons);
    lv_obj_t *ui_page_station_btn_hum_comfort_lbl = lv_label_create(ui_page_station_btn_hum_comfort);
    lv_label_set_text(ui_page_station_btn_hum_comfort_lbl, ui_get_string(UI_STR_STRING_COMFORT));
    lv_obj_center(ui_page_station_btn_hum_comfort_lbl);
    lv_obj_set_style_text_font(ui_page_station_btn_hum_comfort_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_station_btn_hum_comfort, 154, 52);
    lv_obj_set_size(ui_page_station_btn_hum_comfort, 132, 36);
    lv_obj_set_style_bg_color(ui_page_station_btn_hum_comfort, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_hum_comfort, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_btn_hum_comfort, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_hum_comfort, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_btn_hum_comfort, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_station_btn_hum_comfort, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_btn_hum_comfort, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_btn_hum_comfort, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_btn_hum_humid = lv_button_create(ui_page_station_cont_hum_buttons);
    lv_obj_t *ui_page_station_btn_hum_humid_lbl = lv_label_create(ui_page_station_btn_hum_humid);
    lv_label_set_text(ui_page_station_btn_hum_humid_lbl, ui_get_string(UI_STR_STRING_HUMID));
    lv_obj_center(ui_page_station_btn_hum_humid_lbl);
    lv_obj_set_style_text_font(ui_page_station_btn_hum_humid_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_station_btn_hum_humid, 308, 52);
    lv_obj_set_size(ui_page_station_btn_hum_humid, 132, 36);
    lv_obj_set_style_bg_color(ui_page_station_btn_hum_humid, lv_color_hex(0xA78BFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_hum_humid, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_btn_hum_humid, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_hum_humid, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_btn_hum_humid, lv_color_hex(0xA78BFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_station_btn_hum_humid, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_btn_hum_humid, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_btn_hum_humid, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_pos(ui_page_station_cont_hum_buttons, 18, 200);
    lv_obj_set_size(ui_page_station_cont_hum_buttons, 440, 44);

    static lv_point_precise_t ui_page_station_ln_trend_points[] = {{0, 60}, {60, 46}, {120, 50}, {180, 32}, {240, 34}, {300, 18}, {380, 26}, {440, 14}};
    ui_page_station_ln_trend = lv_line_create(ui_page_station_cont_main_right);
    lv_line_set_points(ui_page_station_ln_trend, ui_page_station_ln_trend_points, 8);
    lv_line_set_y_invert(ui_page_station_ln_trend, false);
    lv_obj_set_pos(ui_page_station_ln_trend, 18, 264);
    lv_obj_set_size(ui_page_station_ln_trend, 440, 74);

    lv_obj_set_pos(ui_page_station_cont_main_right, 524, 110);
    lv_obj_set_size(ui_page_station_cont_main_right, 476, 360);
    lv_obj_add_style(ui_page_station_cont_main_right, &ui_style_metric_card, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_cont_footer = lv_obj_create(ui_page_station_cont_root);
    lv_obj_set_style_pad_all(ui_page_station_cont_footer, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_station_cont_footer, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_station_cont_footer, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_station_cont_footer, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    ui_page_station_lbl_date = lv_label_create(ui_page_station_cont_footer);
    lv_label_set_text(ui_page_station_lbl_date, "Wed 27 May");
    lv_obj_set_pos(ui_page_station_lbl_date, 18, 14);
    lv_obj_set_size(ui_page_station_lbl_date, 460, 36);
    lv_obj_set_style_text_color(ui_page_station_lbl_date, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_date, ui_font_montserrat_nearest(26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_date, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_lbl_footer_hint = lv_label_create(ui_page_station_cont_footer);
    lv_label_set_text(ui_page_station_lbl_footer_hint, ui_get_string(UI_STR_STRING_FOOTER_HINT));
    lv_obj_set_pos(ui_page_station_lbl_footer_hint, 500, 16);
    lv_obj_set_size(ui_page_station_lbl_footer_hint, 470, 60);
    lv_obj_set_style_text_color(ui_page_station_lbl_footer_hint, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_footer_hint, ui_font_montserrat_nearest(18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_footer_hint, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_pos(ui_page_station_cont_footer, 17, 498);
    lv_obj_set_size(ui_page_station_cont_footer, 976, 92);

    ui_page_station_cont_header = lv_obj_create(ui_page_station_cont_root);
    lv_obj_set_style_pad_all(ui_page_station_cont_header, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_page_station_cont_header, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_page_station_cont_header, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_flag(ui_page_station_cont_header, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    ui_page_station_lbl_app_title = lv_label_create(ui_page_station_cont_header);
    lv_label_set_text(ui_page_station_lbl_app_title, ui_get_string(UI_STR_STRING_APP_TITLE));
    lv_obj_set_pos(ui_page_station_lbl_app_title, 14, 10);
    lv_obj_set_size(ui_page_station_lbl_app_title, 340, 32);
    lv_obj_set_style_text_color(ui_page_station_lbl_app_title, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_app_title, ui_font_montserrat_nearest(26), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_btn_open_settings = lv_button_create(ui_page_station_cont_header);
    lv_obj_t *ui_page_station_btn_open_settings_lbl = lv_label_create(ui_page_station_btn_open_settings);
    lv_label_set_text(ui_page_station_btn_open_settings_lbl, ui_get_string(UI_STR_STRING_SETTINGS));
    lv_obj_center(ui_page_station_btn_open_settings_lbl);
    lv_obj_set_style_text_font(ui_page_station_btn_open_settings_lbl, ui_font_montserrat_nearest(14), LV_PART_MAIN);
    lv_obj_set_pos(ui_page_station_btn_open_settings, 300, 12);
    lv_obj_set_size(ui_page_station_btn_open_settings, 118, 40);
    lv_obj_set_style_bg_color(ui_page_station_btn_open_settings, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_open_settings, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_btn_open_settings, lv_color_hex(0x2DD4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_btn_open_settings, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_btn_open_settings, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_station_btn_open_settings, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_page_station_btn_open_settings, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_btn_open_settings, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_lbl_clock = lv_label_create(ui_page_station_cont_header);
    lv_label_set_text(ui_page_station_lbl_clock, "08:41");
    lv_obj_set_pos(ui_page_station_lbl_clock, 720, 12);
    lv_obj_set_size(ui_page_station_lbl_clock, 210, 32);
    lv_obj_set_style_text_color(ui_page_station_lbl_clock, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_clock, ui_font_montserrat_nearest(26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_clock, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_anim_t a_ui_page_station_lbl_clock_0;
        lv_anim_init(&a_ui_page_station_lbl_clock_0);
        lv_anim_set_var(&a_ui_page_station_lbl_clock_0, ui_page_station_lbl_clock);
        lv_anim_set_exec_cb(&a_ui_page_station_lbl_clock_0, (lv_anim_exec_xcb_t)ui_anim_opa_cb);
        lv_anim_set_values(&a_ui_page_station_lbl_clock_0, 180, 255);
        lv_anim_set_time(&a_ui_page_station_lbl_clock_0, 700);
        lv_anim_set_path_cb(&a_ui_page_station_lbl_clock_0, lv_anim_path_ease_in_out);
        lv_anim_set_repeat_count(&a_ui_page_station_lbl_clock_0, LV_ANIM_REPEAT_INFINITE);
        lv_anim_start(&a_ui_page_station_lbl_clock_0);
    }

    ui_page_station_spn_refresh = lv_spinner_create(ui_page_station_cont_header);
    lv_spinner_set_anim_params(ui_page_station_spn_refresh, 900, 62);
    lv_obj_set_pos(ui_page_station_spn_refresh, 792, 8);
    lv_obj_set_size(ui_page_station_spn_refresh, 38, 38);
    lv_obj_set_style_bg_color(ui_page_station_spn_refresh, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_spn_refresh, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_station_spn_refresh, lv_color_hex(0xA78BFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_station_spn_refresh, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_station_spn_refresh, lv_color_hex(0x1F2A44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_page_station_spn_refresh, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_station_sw_night = lv_switch_create(ui_page_station_cont_header);
    lv_obj_add_state(ui_page_station_sw_night, LV_STATE_CHECKED);
    lv_obj_set_pos(ui_page_station_sw_night, 662, 18);
    lv_obj_set_size(ui_page_station_sw_night, 48, 28);

    ui_page_station_lbl_night = lv_label_create(ui_page_station_cont_header);
    lv_label_set_text(ui_page_station_lbl_night, ui_get_string(UI_STR_STRING_NIGHT));
    lv_obj_set_pos(ui_page_station_lbl_night, 548, 18);
    lv_obj_set_size(ui_page_station_lbl_night, 108, 28);
    lv_obj_set_style_text_color(ui_page_station_lbl_night, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page_station_lbl_night, ui_font_montserrat_nearest(18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_page_station_lbl_night, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_pos(ui_page_station_cont_header, 24, 18);
    lv_obj_set_size(ui_page_station_cont_header, 976, 64);
    lv_obj_add_style(ui_page_station_cont_header, &ui_style_header_card, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_pos(ui_page_station_cont_root, 0, 0);
    lv_obj_set_size(ui_page_station_cont_root, 1024, 600);
    lv_obj_add_style(ui_page_station_cont_root, &ui_style_app_bg, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Event registrations */
    lv_obj_add_event_cb(ui_page_station_btn_cool_1, ui_page_station_btn_cool_1_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_station_btn_mild_1, ui_page_station_btn_mild_1_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_station_btn_hot_1, ui_page_station_btn_hot_1_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_station_btn_reset_temp, ui_page_station_btn_reset_temp_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_station_btn_play_anim_hint, ui_page_station_btn_play_anim_hint_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_station_btn_hum_dry, ui_page_station_btn_hum_dry_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_station_btn_hum_comfort, ui_page_station_btn_hum_comfort_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_station_btn_hum_humid, ui_page_station_btn_hum_humid_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_station_btn_open_settings, ui_page_station_btn_open_settings_on_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_page_station_sw_night, ui_page_station_sw_night_on_value_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_page_station, ui_page_station_on_swipe, LV_EVENT_GESTURE, NULL);
    /* Exclusive button groups — design default */
    ui_page_station_select_group_0(ui_page_station_btn_hot_1);
    ui_page_station_select_group_1(ui_page_station_btn_hum_humid);

}
