/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#ifndef UI_PAGE_SETTINGS_H
#define UI_PAGE_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

/** Screen object for page "Settings" */
extern lv_obj_t *ui_page_settings;

/* Widget objects */
extern lv_obj_t *ui_page_settings_cont_settings_root;
extern lv_obj_t *ui_page_settings_cont_settings_header;
extern lv_obj_t *ui_page_settings_lbl_settings_title;
extern lv_obj_t *ui_page_settings_lbl_settings_sub;
extern lv_obj_t *ui_page_settings_btn_back_station;
extern lv_obj_t *ui_page_settings_ln_settings_sep;
extern lv_obj_t *ui_page_settings_cont_settings_body;
extern lv_obj_t *ui_page_settings_lbl_language_title;
extern lv_obj_t *ui_page_settings_lbl_language_hint;
extern lv_obj_t *ui_page_settings_btn_lang_en;
extern lv_obj_t *ui_page_settings_btn_lang_de;
extern lv_obj_t *ui_page_settings_btn_lang_fa;
extern lv_obj_t *ui_page_settings_ln_settings_divider;
extern lv_obj_t *ui_page_settings_lbl_dark_mode;
extern lv_obj_t *ui_page_settings_sw_dark_theme;
extern lv_obj_t *ui_page_settings_lbl_brightness;
extern lv_obj_t *ui_page_settings_lbl_brightness_val;
extern lv_obj_t *ui_page_settings_slider_brightness;

/** Create all widgets for the "Settings" screen. */
void ui_page_settings_screen_init(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* UI_PAGE_SETTINGS_H */
