/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#include "ui_rtl_fonts.h"

const lv_font_t *ui_font_montserrat_plain(uint8_t size)
{
    uint8_t best = 14;
    uint8_t best_diff = 255;
    static const uint8_t available[] = { 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48 };
    for (unsigned i = 0; i < sizeof(available) / sizeof(available[0]); i++) {
        uint8_t d = (size > available[i]) ? (size - available[i]) : (available[i] - size);
        if (d < best_diff) {
            best_diff = d;
            best = available[i];
        }
    }
    switch (best) {
#if LV_FONT_MONTSERRAT_8
        case 8: return &lv_font_montserrat_8;
#endif
#if LV_FONT_MONTSERRAT_10
        case 10: return &lv_font_montserrat_10;
#endif
#if LV_FONT_MONTSERRAT_12
        case 12: return &lv_font_montserrat_12;
#endif
#if LV_FONT_MONTSERRAT_14
        case 14: return &lv_font_montserrat_14;
#endif
#if LV_FONT_MONTSERRAT_16
        case 16: return &lv_font_montserrat_16;
#endif
#if LV_FONT_MONTSERRAT_18
        case 18: return &lv_font_montserrat_18;
#endif
#if LV_FONT_MONTSERRAT_20
        case 20: return &lv_font_montserrat_20;
#endif
#if LV_FONT_MONTSERRAT_22
        case 22: return &lv_font_montserrat_22;
#endif
#if LV_FONT_MONTSERRAT_24
        case 24: return &lv_font_montserrat_24;
#endif
#if LV_FONT_MONTSERRAT_26
        case 26: return &lv_font_montserrat_26;
#endif
#if LV_FONT_MONTSERRAT_28
        case 28: return &lv_font_montserrat_28;
#endif
#if LV_FONT_MONTSERRAT_30
        case 30: return &lv_font_montserrat_30;
#endif
#if LV_FONT_MONTSERRAT_32
        case 32: return &lv_font_montserrat_32;
#endif
#if LV_FONT_MONTSERRAT_34
        case 34: return &lv_font_montserrat_34;
#endif
#if LV_FONT_MONTSERRAT_36
        case 36: return &lv_font_montserrat_36;
#endif
#if LV_FONT_MONTSERRAT_38
        case 38: return &lv_font_montserrat_38;
#endif
#if LV_FONT_MONTSERRAT_40
        case 40: return &lv_font_montserrat_40;
#endif
#if LV_FONT_MONTSERRAT_42
        case 42: return &lv_font_montserrat_42;
#endif
#if LV_FONT_MONTSERRAT_44
        case 44: return &lv_font_montserrat_44;
#endif
#if LV_FONT_MONTSERRAT_46
        case 46: return &lv_font_montserrat_46;
#endif
#if LV_FONT_MONTSERRAT_48
        case 48: return &lv_font_montserrat_48;
#endif
        default: break;
    }
    return LV_FONT_DEFAULT;
}

#if LV_FONT_DEJAVU_16_PERSIAN_HEBREW

#if LV_FONT_MONTSERRAT_12
extern const lv_font_t embf_font_latin1_12;
#endif
#if LV_FONT_MONTSERRAT_14
extern const lv_font_t embf_font_latin1_14;
#endif
#if LV_FONT_MONTSERRAT_16
extern const lv_font_t embf_font_latin1_16;
#endif
#if LV_FONT_MONTSERRAT_18
extern const lv_font_t embf_font_latin1_18;
#endif
#if LV_FONT_MONTSERRAT_20
extern const lv_font_t embf_font_latin1_20;
#endif
#if LV_FONT_MONTSERRAT_24
extern const lv_font_t embf_font_latin1_24;
#endif
#if LV_FONT_MONTSERRAT_32
extern const lv_font_t embf_font_latin1_32;
#endif
#if LV_FONT_MONTSERRAT_48
extern const lv_font_t embf_font_latin1_48;
#endif

#if LV_FONT_MONTSERRAT_12
static lv_font_t ui_f_latin_12;
static lv_font_t ui_f_ms_12;
#endif
#if LV_FONT_MONTSERRAT_14
static lv_font_t ui_f_latin_14;
static lv_font_t ui_f_ms_14;
#endif
#if LV_FONT_MONTSERRAT_16
static lv_font_t ui_f_latin_16;
static lv_font_t ui_f_ms_16;
#endif
#if LV_FONT_MONTSERRAT_18
static lv_font_t ui_f_latin_18;
static lv_font_t ui_f_ms_18;
#endif
#if LV_FONT_MONTSERRAT_20
static lv_font_t ui_f_latin_20;
static lv_font_t ui_f_ms_20;
#endif
#if LV_FONT_MONTSERRAT_24
static lv_font_t ui_f_latin_24;
static lv_font_t ui_f_ms_24;
#endif
#if LV_FONT_MONTSERRAT_32
static lv_font_t ui_f_latin_32;
static lv_font_t ui_f_ms_32;
#endif
#if LV_FONT_MONTSERRAT_48
static lv_font_t ui_f_latin_48;
static lv_font_t ui_f_ms_48;
#endif

void ui_rtl_fonts_init(void)
{
#if LV_FONT_MONTSERRAT_12
    ui_f_latin_12 = embf_font_latin1_12;
    ui_f_latin_12.fallback = &lv_font_dejavu_16_persian_hebrew;
    ui_f_ms_12 = lv_font_montserrat_12;
    ui_f_ms_12.fallback = &ui_f_latin_12;
#endif
#if LV_FONT_MONTSERRAT_14
    ui_f_latin_14 = embf_font_latin1_14;
    ui_f_latin_14.fallback = &lv_font_dejavu_16_persian_hebrew;
    ui_f_ms_14 = lv_font_montserrat_14;
    ui_f_ms_14.fallback = &ui_f_latin_14;
#endif
#if LV_FONT_MONTSERRAT_16
    ui_f_latin_16 = embf_font_latin1_16;
    ui_f_latin_16.fallback = &lv_font_dejavu_16_persian_hebrew;
    ui_f_ms_16 = lv_font_montserrat_16;
    ui_f_ms_16.fallback = &ui_f_latin_16;
#endif
#if LV_FONT_MONTSERRAT_18
    ui_f_latin_18 = embf_font_latin1_18;
    ui_f_latin_18.fallback = &lv_font_dejavu_16_persian_hebrew;
    ui_f_ms_18 = lv_font_montserrat_18;
    ui_f_ms_18.fallback = &ui_f_latin_18;
#endif
#if LV_FONT_MONTSERRAT_20
    ui_f_latin_20 = embf_font_latin1_20;
    ui_f_latin_20.fallback = &lv_font_dejavu_16_persian_hebrew;
    ui_f_ms_20 = lv_font_montserrat_20;
    ui_f_ms_20.fallback = &ui_f_latin_20;
#endif
#if LV_FONT_MONTSERRAT_24
    ui_f_latin_24 = embf_font_latin1_24;
    ui_f_latin_24.fallback = &lv_font_dejavu_16_persian_hebrew;
    ui_f_ms_24 = lv_font_montserrat_24;
    ui_f_ms_24.fallback = &ui_f_latin_24;
#endif
#if LV_FONT_MONTSERRAT_32
    ui_f_latin_32 = embf_font_latin1_32;
    ui_f_latin_32.fallback = &lv_font_dejavu_16_persian_hebrew;
    ui_f_ms_32 = lv_font_montserrat_32;
    ui_f_ms_32.fallback = &ui_f_latin_32;
#endif
#if LV_FONT_MONTSERRAT_48
    ui_f_latin_48 = embf_font_latin1_48;
    ui_f_latin_48.fallback = &lv_font_dejavu_16_persian_hebrew;
    ui_f_ms_48 = lv_font_montserrat_48;
    ui_f_ms_48.fallback = &ui_f_latin_48;
#endif
}

const lv_font_t *ui_font_montserrat_nearest(uint8_t size)
{
#if LV_FONT_DEJAVU_16_PERSIAN_HEBREW
#if LV_FONT_MONTSERRAT_12
    if (size <= 12) return &ui_f_ms_12;
#endif
#if LV_FONT_MONTSERRAT_14
    if (size <= 15) return &ui_f_ms_14;
#endif
#if LV_FONT_MONTSERRAT_16
    if (size <= 17) return &ui_f_ms_16;
#endif
#if LV_FONT_MONTSERRAT_18
    if (size <= 19) return &ui_f_ms_18;
#endif
#if LV_FONT_MONTSERRAT_20
    if (size <= 22) return &ui_f_ms_20;
#endif
#if LV_FONT_MONTSERRAT_24
    if (size <= 28) return &ui_f_ms_24;
#endif
#if LV_FONT_MONTSERRAT_32
    if (size <= 40) return &ui_f_ms_32;
#endif
#if LV_FONT_MONTSERRAT_48
    if (size <= 255) return &ui_f_ms_48;
#endif
    return UI_FONT_BIDI;
#else
    return ui_font_montserrat_plain(size);
#endif
}

#else /* LV_FONT_DEJAVU_16_PERSIAN_HEBREW */

void ui_rtl_fonts_init(void)
{
}

const lv_font_t *ui_font_montserrat_nearest(uint8_t size)
{
    return ui_font_montserrat_plain(size);
}

#endif

/*
 * Compile these Latin-1 supplement fonts into your firmware (alongside ui_rtl_fonts.c):
 *   embf_font_latin1_12.c
 *   embf_font_latin1_14.c
 *   embf_font_latin1_16.c
 *   embf_font_latin1_18.c
 *   embf_font_latin1_20.c
 *   embf_font_latin1_24.c
 *   embf_font_latin1_32.c
 *   embf_font_latin1_48.c
 * Chain: Montserrat → embf_font_latin1_* (0xC0-0xFF) → lv_font_dejavu_16_persian_hebrew
 */
