/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#ifndef UI_RTL_FONTS_H
#define UI_RTL_FONTS_H

#include "lvgl.h"
#include <stdint.h>

/* Requires LV_FONT_DEJAVU_16_PERSIAN_HEBREW 1 in lv_conf / sdkconfig. */
#if LV_FONT_DEJAVU_16_PERSIAN_HEBREW
#define UI_FONT_BIDI  (&lv_font_dejavu_16_persian_hebrew)
#else
#define UI_FONT_BIDI  LV_FONT_DEFAULT
#endif

/** Wire Montserrat → Latin-1 → DejaVu fallback (call once from ui_init before widgets). */
void ui_rtl_fonts_init(void);

/** Built-in Montserrat only (no fallbacks). */
const lv_font_t *ui_font_montserrat_plain(uint8_t size);

/** Montserrat + Latin-1 + DejaVu fallback — use for all localized text. */
const lv_font_t *ui_font_montserrat_nearest(uint8_t size);

#endif /* UI_RTL_FONTS_H */
