/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#ifndef UI_STYLES_H
#define UI_STYLES_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

/* Named lv_style_t objects defined in ui_styles.c. */
extern lv_style_t ui_style_app_bg;
extern lv_style_t ui_style_header_card;
extern lv_style_t ui_style_metric_card;
extern lv_style_t ui_style_muted_text;
extern lv_style_t ui_style_title_text;
extern lv_style_t ui_style_value_glow;
extern lv_style_t ui_style_unit_text;
extern lv_style_t ui_style_chip;
extern lv_style_t ui_style_divider_line;

/** Initialise every named style. Call once from ui_init() before screen creation. */
void ui_styles_init(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* UI_STYLES_H */
