/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#ifndef UI_STRINGS_H
#define UI_STRINGS_H

#include "lvgl.h"
#include "ui_strings_ids.h"

typedef enum {
#define X(id) id,
    UI_STRING_KEYS
#undef X
    UI_STR_COUNT
} ui_string_id_t;

const char *ui_get_string(ui_string_id_t id);

/** Select active locale at runtime (must match a locale id in strings.res). */
void ui_set_locale(const char *locale_id);

/** Current locale id, or "" if unknown. */
const char *ui_get_active_locale(void);

/** Re-apply ui_get_string() on every widget that references a string resource key. */
void ui_refresh_localized_text(void);

/** Resolve base text direction for the active locale (RTL6). */
lv_base_dir_t ui_resolve_base_dir(void);

/** Apply ui_resolve_base_dir() to localized text widgets (layout stays LTR). */
void ui_apply_text_direction(void);

/** Call once from ui_init() — selects defaultLocale from strings.res. */
void ui_strings_init(void);

#endif /* UI_STRINGS_H */
