/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#include "ui_styles.h"

lv_style_t ui_style_app_bg;
lv_style_t ui_style_header_card;
lv_style_t ui_style_metric_card;
lv_style_t ui_style_muted_text;
lv_style_t ui_style_title_text;
lv_style_t ui_style_value_glow;
lv_style_t ui_style_unit_text;
lv_style_t ui_style_chip;
lv_style_t ui_style_divider_line;

void ui_styles_init(void)
{
    /* app_bg — App background */
    lv_style_init(&ui_style_app_bg);
    lv_style_set_bg_color(&ui_style_app_bg, lv_color_hex(0x070A12));
    lv_style_set_bg_opa(&ui_style_app_bg, LV_OPA_COVER);
    lv_style_set_bg_opa(&ui_style_app_bg, 255);
    lv_style_set_radius(&ui_style_app_bg, 0);

    /* header_card — Header card */
    lv_style_init(&ui_style_header_card);
    lv_style_set_bg_color(&ui_style_header_card, lv_color_hex(0x0F172A));
    lv_style_set_bg_opa(&ui_style_header_card, LV_OPA_COVER);
    lv_style_set_bg_opa(&ui_style_header_card, 235);
    lv_style_set_border_color(&ui_style_header_card, lv_color_hex(0x1F2A44));
    lv_style_set_border_width(&ui_style_header_card, 2);
    lv_style_set_radius(&ui_style_header_card, 18);
    lv_style_set_pad_all(&ui_style_header_card, 14);

    /* metric_card — Metric card */
    lv_style_init(&ui_style_metric_card);
    lv_style_set_bg_color(&ui_style_metric_card, lv_color_hex(0x0B1222));
    lv_style_set_bg_opa(&ui_style_metric_card, LV_OPA_COVER);
    lv_style_set_bg_opa(&ui_style_metric_card, 235);
    lv_style_set_border_color(&ui_style_metric_card, lv_color_hex(0x1F2A44));
    lv_style_set_border_width(&ui_style_metric_card, 2);
    lv_style_set_radius(&ui_style_metric_card, 22);
    lv_style_set_pad_all(&ui_style_metric_card, 18);

    /* muted_text — Muted text */
    lv_style_init(&ui_style_muted_text);
    lv_style_set_text_color(&ui_style_muted_text, lv_color_hex(0x94A3B8));
    lv_style_set_text_align(&ui_style_muted_text, LV_TEXT_ALIGN_LEFT);

    /* title_text — Title text */
    lv_style_init(&ui_style_title_text);
    lv_style_set_text_color(&ui_style_title_text, lv_color_hex(0xE5E7EB));
    lv_style_set_text_align(&ui_style_title_text, LV_TEXT_ALIGN_LEFT);

    /* value_glow — Value glow text */
    lv_style_init(&ui_style_value_glow);
    lv_style_set_text_color(&ui_style_value_glow, lv_color_hex(0x2DD4FF));
    lv_style_set_text_align(&ui_style_value_glow, LV_TEXT_ALIGN_CENTER);

    /* unit_text — Unit text */
    lv_style_init(&ui_style_unit_text);
    lv_style_set_text_color(&ui_style_unit_text, lv_color_hex(0xA78BFA));
    lv_style_set_text_align(&ui_style_unit_text, LV_TEXT_ALIGN_CENTER);

    /* chip — Info chip */
    lv_style_init(&ui_style_chip);
    lv_style_set_bg_color(&ui_style_chip, lv_color_hex(0x0F172A));
    lv_style_set_bg_opa(&ui_style_chip, LV_OPA_COVER);
    lv_style_set_bg_opa(&ui_style_chip, 240);
    lv_style_set_border_color(&ui_style_chip, lv_color_hex(0x1F2A44));
    lv_style_set_border_width(&ui_style_chip, 1);
    lv_style_set_radius(&ui_style_chip, 16);
    lv_style_set_text_color(&ui_style_chip, lv_color_hex(0xE5E7EB));
    lv_style_set_pad_all(&ui_style_chip, 10);

    /* divider_line — Divider line */
    lv_style_init(&ui_style_divider_line);
    lv_style_set_bg_color(&ui_style_divider_line, lv_color_hex(0x1F2A44));
    lv_style_set_bg_opa(&ui_style_divider_line, LV_OPA_COVER);
    lv_style_set_bg_opa(&ui_style_divider_line, 255);
    lv_style_set_border_color(&ui_style_divider_line, lv_color_hex(0x1F2A44));
    lv_style_set_border_width(&ui_style_divider_line, 2);
    lv_style_set_radius(&ui_style_divider_line, 8);

}
