/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

/* ui.h pulls in page widget externs used below. */
#include "ui.h"
#include "ui_strings.h"

/** Text direction on the widget only — screen layout stays LTR (absolute positions). */
static void ui_apply_localized_label_style(lv_obj_t *obj, uint8_t font_px, lv_text_align_t align_hint)
{
    if (obj == NULL) {
        return;
    }
    lv_base_dir_t dir = ui_resolve_base_dir();
    lv_obj_set_style_base_dir(obj, dir, LV_PART_MAIN);
    lv_text_align_t align = align_hint;
    if (align_hint == LV_TEXT_ALIGN_AUTO) {
        align = (dir == LV_BASE_DIR_RTL) ? LV_TEXT_ALIGN_RIGHT : LV_TEXT_ALIGN_LEFT;
    }
    lv_obj_set_style_text_align(obj, align, LV_PART_MAIN);
    lv_obj_set_style_text_font(obj, ui_font_montserrat_nearest(font_px), LV_PART_MAIN);
    if (lv_obj_check_type(obj, &lv_label_class)) {
        lv_label_set_long_mode(obj, LV_LABEL_LONG_WRAP);
    }
}

static void ui_apply_localized_button_label_style(lv_obj_t *child, uint8_t font_px)
{
    if (child == NULL) {
        return;
    }
    lv_base_dir_t dir = ui_resolve_base_dir();
    lv_obj_set_style_base_dir(child, dir, LV_PART_MAIN);
    lv_obj_set_style_text_font(child, ui_font_montserrat_nearest(font_px), LV_PART_MAIN);
}

/** Button labels are created as child lv_label objects in page init (not file-scope globals). */
static void ui_set_button_label(lv_obj_t *btn, const char *text, uint8_t font_px)
{
    if (btn == NULL || text == NULL) {
        return;
    }
    const uint32_t n = lv_obj_get_child_cnt(btn);
    for (uint32_t i = 0; i < n; i++) {
        lv_obj_t *child = lv_obj_get_child(btn, i);
        if (child != NULL && lv_obj_check_type(child, &lv_label_class)) {
            lv_label_set_text(child, text);
            ui_apply_localized_button_label_style(child, font_px);
            lv_obj_center(child);
            return;
        }
    }
}
void ui_refresh_localized_text(void)
{
    if (ui_page_station_lbl_temp_title) { lv_label_set_text(ui_page_station_lbl_temp_title, ui_get_string(UI_STR_STRING_TEMPERATURE)); ui_apply_localized_label_style(ui_page_station_lbl_temp_title, 22, LV_TEXT_ALIGN_AUTO); }
    if (ui_page_station_lbl_temp_range) { lv_label_set_text(ui_page_station_lbl_temp_range, ui_get_string(UI_STR_STRING_TEMP_RANGE)); ui_apply_localized_label_style(ui_page_station_lbl_temp_range, 18, LV_TEXT_ALIGN_LEFT); }
    ui_set_button_label(ui_page_station_btn_cool_1, ui_get_string(UI_STR_STRING_COOL), 14);
    ui_set_button_label(ui_page_station_btn_mild_1, ui_get_string(UI_STR_STRING_MILD), 14);
    ui_set_button_label(ui_page_station_btn_hot_1, ui_get_string(UI_STR_STRING_HOT), 14);
    ui_set_button_label(ui_page_station_btn_reset_temp, ui_get_string(UI_STR_STRING_RESET), 14);
    ui_set_button_label(ui_page_station_btn_play_anim_hint, ui_get_string(UI_STR_STRING_PLAY_ANIMS), 14);
    if (ui_page_station_lbl_hum_title) { lv_label_set_text(ui_page_station_lbl_hum_title, ui_get_string(UI_STR_STRING_HUMIDITY)); ui_apply_localized_label_style(ui_page_station_lbl_hum_title, 22, LV_TEXT_ALIGN_AUTO); }
    if (ui_page_station_lbl_hum_status) { lv_label_set_text(ui_page_station_lbl_hum_status, ui_get_string(UI_STR_STRING_COMFORT)); ui_apply_localized_label_style(ui_page_station_lbl_hum_status, 22, LV_TEXT_ALIGN_LEFT); }
    ui_set_button_label(ui_page_station_btn_hum_dry, ui_get_string(UI_STR_STRING_DRY), 14);
    ui_set_button_label(ui_page_station_btn_hum_comfort, ui_get_string(UI_STR_STRING_COMFORT), 14);
    ui_set_button_label(ui_page_station_btn_hum_humid, ui_get_string(UI_STR_STRING_HUMID), 14);
    if (ui_page_station_lbl_footer_hint) { lv_label_set_text(ui_page_station_lbl_footer_hint, ui_get_string(UI_STR_STRING_FOOTER_HINT)); ui_apply_localized_label_style(ui_page_station_lbl_footer_hint, 18, LV_TEXT_ALIGN_RIGHT); }
    if (ui_page_station_lbl_app_title) { lv_label_set_text(ui_page_station_lbl_app_title, ui_get_string(UI_STR_STRING_APP_TITLE)); ui_apply_localized_label_style(ui_page_station_lbl_app_title, 26, LV_TEXT_ALIGN_AUTO); }
    ui_set_button_label(ui_page_station_btn_open_settings, ui_get_string(UI_STR_STRING_SETTINGS), 14);
    if (ui_page_station_lbl_night) { lv_label_set_text(ui_page_station_lbl_night, ui_get_string(UI_STR_STRING_NIGHT)); ui_apply_localized_label_style(ui_page_station_lbl_night, 18, LV_TEXT_ALIGN_LEFT); }
    if (ui_page_settings_lbl_settings_title) { lv_label_set_text(ui_page_settings_lbl_settings_title, ui_get_string(UI_STR_STRING_SETTINGS_TITLE)); ui_apply_localized_label_style(ui_page_settings_lbl_settings_title, 26, LV_TEXT_ALIGN_AUTO); }
    if (ui_page_settings_lbl_settings_sub) { lv_label_set_text(ui_page_settings_lbl_settings_sub, ui_get_string(UI_STR_STRING_SETTINGS_SUB)); ui_apply_localized_label_style(ui_page_settings_lbl_settings_sub, 16, LV_TEXT_ALIGN_AUTO); }
    ui_set_button_label(ui_page_settings_btn_back_station, ui_get_string(UI_STR_STRING_BACK), 14);
    if (ui_page_settings_lbl_language_title) { lv_label_set_text(ui_page_settings_lbl_language_title, ui_get_string(UI_STR_STRING_LANGUAGE)); ui_apply_localized_label_style(ui_page_settings_lbl_language_title, 22, LV_TEXT_ALIGN_AUTO); }
    if (ui_page_settings_lbl_language_hint) { lv_label_set_text(ui_page_settings_lbl_language_hint, ui_get_string(UI_STR_STRING_LANGUAGE_HINT)); ui_apply_localized_label_style(ui_page_settings_lbl_language_hint, 16, LV_TEXT_ALIGN_AUTO); }
    ui_set_button_label(ui_page_settings_btn_lang_en, ui_get_string(UI_STR_STRING_ENGLISH), 14);
    ui_set_button_label(ui_page_settings_btn_lang_de, ui_get_string(UI_STR_STRING_GERMAN), 14);
    ui_set_button_label(ui_page_settings_btn_lang_fa, ui_get_string(UI_STR_STRING_PERSIAN), 14);
    lv_obj_invalidate(lv_screen_active());
}
