/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */

#include "ui_strings.h"
#include "ui.h"
#include <string.h>

typedef struct {
    const char *id;
    int rtl; /* 1 = rtl, 0 = ltr */
} ui_locale_dir_entry_t;

static const ui_locale_dir_entry_t ui_locale_dir_meta[] = {
    { "fa", 1 }
};

static int ui_locale_meta_is_rtl(const char *locale_id)
{
    if (!locale_id) return -1;
    for (unsigned i = 0; i < sizeof(ui_locale_dir_meta) / sizeof(ui_locale_dir_meta[0]); i++) {
        if (strcmp(locale_id, ui_locale_dir_meta[i].id) == 0) {
            return ui_locale_dir_meta[i].rtl;
        }
    }
    return -1;
}

static int ui_locale_id_inferred_rtl(const char *locale_id)
{
    if (!locale_id || !locale_id[0]) return 0;
    static const char *const bases[] = { "ar", "dv", "fa", "he", "ku", "ps", "ur" };
    for (unsigned i = 0; i < sizeof(bases) / sizeof(bases[0]); i++) {
        size_t n = strlen(bases[i]);
        if (strncmp(locale_id, bases[i], n) != 0) continue;
        if (locale_id[n] == '\0' || locale_id[n] == '-' || locale_id[n] == '_') return 1;
    }
    return 0;
}

lv_base_dir_t ui_resolve_base_dir(void)
{
    const char *loc = ui_get_active_locale();
    if (loc && loc[0]) {
        int meta = ui_locale_meta_is_rtl(loc);
        if (meta >= 0) {
            return meta ? LV_BASE_DIR_RTL : LV_BASE_DIR_LTR;
        }
        if (ui_locale_id_inferred_rtl(loc)) {
            return LV_BASE_DIR_RTL;
        }
    }
    return LV_BASE_DIR_LTR;
}

void ui_apply_text_direction(void)
{
    /* Absolute-position layouts stay LTR; localized labels get dir in ui_refresh_localized_text(). */
    ui_refresh_localized_text();
}

static void ui_locale_apply_async_cb(void *user_data)
{
    (void)user_data;
    ui_refresh_localized_text();
}

#include "ui_strings_de.def"
static const char *const ui_strings_table_de[UI_STR_COUNT] = {
#define X(id, text) text,
    UI_STRING_LIST_DE
#undef X
};

#include "ui_strings_en.def"
static const char *const ui_strings_table_en[UI_STR_COUNT] = {
#define X(id, text) text,
    UI_STRING_LIST_EN
#undef X
};

#include "ui_strings_fa.def"
static const char *const ui_strings_table_fa[UI_STR_COUNT] = {
#define X(id, text) text,
    UI_STRING_LIST_FA
#undef X
};

typedef struct {
    const char *id;
    const char *const *table;
} ui_locale_entry_t;

static const ui_locale_entry_t ui_locale_entries[] = {
    { "de", ui_strings_table_de },
    { "en", ui_strings_table_en },
    { "fa", ui_strings_table_fa }
};

static const char *const *ui_strings_active = ui_strings_table_en;
static const char *ui_active_locale_id = "en";

void ui_strings_init(void)
{
    /* Default locale table is selected by static initializers; do not refresh here —
     * widgets are not created until after ui_strings_init() returns from ui_init(). */
}

void ui_set_locale(const char *locale_id)
{
    if (!locale_id) {
        return;
    }
    for (unsigned i = 0; i < sizeof(ui_locale_entries) / sizeof(ui_locale_entries[0]); i++) {
        if (strcmp(locale_id, ui_locale_entries[i].id) == 0) {
            ui_strings_active = ui_locale_entries[i].table;
            ui_active_locale_id = ui_locale_entries[i].id;
            lv_async_call(ui_locale_apply_async_cb, NULL);
            return;
        }
    }
}

const char *ui_get_active_locale(void)
{
    return ui_active_locale_id;
}

const char *ui_get_string(ui_string_id_t id)
{
    if (!ui_strings_active || (unsigned)id >= (unsigned)UI_STR_COUNT) {
        return "";
    }
    return ui_strings_active[id];
}
