import type { DataField, EmbfProject, LabelComponent } from "../types/embf";
import { lvglIncludeDirective } from "./lvglInclude";
import { screenInitFn, widgetVar } from "./naming";

const AUTOGEN_BANNER = `/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */
`;

const BINDING_RE = /\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}/g;

/** Canonical C identifier for a data field. */
export function dataVarName(id: string): string {
    return `ui_data_${id}`;
}

export function dataSetterName(id: string): string {
    return `ui_set_${id}`;
}

export function dataGetterName(id: string): string {
    return `ui_get_${id}`;
}

/** Type used in setter parameters / getters. */
function cTypeFor(field: DataField): string {
    switch (field.type) {
        case "string":
            return "const char *";
        case "int":
            return "int32_t";
        case "float":
            return "float";
        case "bool":
            return "bool";
    }
}

function stringFieldBufSize(field: DataField): number {
    const def =
        field.default !== undefined && field.default !== null ? String(field.default) : "";
    return Math.max(16, Math.min(128, def.length + 12));
}

function formatDefault(field: DataField): string {
    if (field.default === undefined) {
        switch (field.type) {
            case "string":
                return `""`;
            case "int":
                return "0";
            case "float":
                return "0.0f";
            case "bool":
                return "false";
        }
    }
    switch (field.type) {
        case "string":
            return JSON.stringify(field.default);
        case "int":
            return String(Math.round(field.default as number));
        case "float": {
            const n = field.default as number;
            return Number.isInteger(n) ? `${n}.0f` : `${n}f`;
        }
        case "bool":
            return field.default ? "true" : "false";
    }
}

interface LabelBindingRef {
    pageId: string;
    componentId: string;
    text: string;
    fields: string[];
    fieldDefs: Map<string, DataField>;
}

interface NumericBindingRef {
    pageId: string;
    componentId: string;
    /** Source widget type — picks the right `lv_*_set_value` setter. */
    widgetType: "slider" | "bar" | "arc" | "knob";
    fieldId: string;
    fieldType: "int" | "float" | "string" | "bool";
}

const NUMERIC_WIDGETS = new Set(["slider", "bar", "arc", "knob"] as const);

/** Walk the page tree and collect widgets that bind a numeric `value` to a data field. */
function collectNumericBindings(project: EmbfProject): NumericBindingRef[] {
    const refs: NumericBindingRef[] = [];
    const fieldType = new Map<string, DataField["type"]>();
    for (const f of project.dataModel?.fields ?? []) {
        fieldType.set(f.id, f.type);
    }
    for (const page of project.pages) {
        function walk(comps: any[]): void {
            for (const c of comps) {
                const ty = c.type as string;
                const fieldId = c.bindings?.value;
                if (NUMERIC_WIDGETS.has(ty as any) && typeof fieldId === "string") {
                    refs.push({
                        pageId: page.id,
                        componentId: c.id,
                        widgetType: ty as NumericBindingRef["widgetType"],
                        fieldId,
                        fieldType: fieldType.get(fieldId) ?? "int"
                    });
                }
                if (Array.isArray(c.children)) {
                    walk(c.children);
                }
            }
        }
        walk(page.components);
    }
    return refs;
}

/** Walk the page tree and collect labels whose `text` contains at least one `{{field}}`. */
function collectLabelBindings(project: EmbfProject): LabelBindingRef[] {
    const refs: LabelBindingRef[] = [];
    const fieldDefs = new Map<string, DataField>();
    for (const f of project.dataModel?.fields ?? []) {
        fieldDefs.set(f.id, f);
    }
    for (const page of project.pages) {
        function walk(comps: any[]): void {
            for (const c of comps) {
                if (c.type === "label" && typeof c.text === "string") {
                    const fields = extractFieldRefs(c.text as string);
                    if (fields.length > 0) {
                        refs.push({
                            pageId: page.id,
                            componentId: c.id,
                            text: c.text,
                            fields,
                            fieldDefs
                        });
                    }
                }
                if (Array.isArray(c.children)) {
                    walk(c.children);
                }
            }
        }
        walk(page.components);
    }
    return refs;
}

function extractFieldRefs(text: string): string[] {
    const found: string[] = [];
    let m: RegExpExecArray | null;
    const re = new RegExp(BINDING_RE.source, "g");
    while ((m = re.exec(text)) !== null) {
        if (!found.includes(m[1])) {
            found.push(m[1]);
        }
    }
    return found;
}

/** True if the project declares any binding-aware artefacts. */
export function hasBindings(project: EmbfProject): boolean {
    const fields = project.dataModel?.fields ?? [];
    if (fields.length === 0) {
        return false;
    }
    return collectLabelBindings(project).length > 0
        || collectNumericBindings(project).length > 0
        || fields.length > 0;
}

export function generateBindingsHeader(project: EmbfProject): string | null {
    const fields = project.dataModel?.fields ?? [];
    if (fields.length === 0) {
        return null;
    }
    const externs: string[] = [];
    const setters: string[] = [];
    const getters: string[] = [];
    for (const f of fields) {
        if (f.type === "string") {
            externs.push(`extern char ${dataVarName(f.id)}[${stringFieldBufSize(f)}];`);
            setters.push(`void ${dataSetterName(f.id)}(const char *value);`);
            getters.push(`const char *${dataGetterName(f.id)}(void);`);
        } else {
            const cType = cTypeFor(f);
            const sp = cType.endsWith("*") ? "" : " ";
            externs.push(`extern ${cType}${sp}${dataVarName(f.id)};`);
            setters.push(`void ${dataSetterName(f.id)}(${cType}${sp}value);`);
            getters.push(`${cType}${sp}${dataGetterName(f.id)}(void);`);
        }
    }
    return [
        AUTOGEN_BANNER,
        `#ifndef UI_BINDINGS_H`,
        `#define UI_BINDINGS_H`,
        ``,
        `#ifdef __cplusplus`,
        `extern "C" {`,
        `#endif`,
        ``,
        `#include <stdbool.h>`,
        `#include <stdint.h>`,
        lvglIncludeDirective(project),
        ``,
        `/** Backing storage for project.dataModel.fields — read-only from app code; use setters to update. */`,
        ...externs,
        ``,
        `/** Initialise backing storage to declared defaults. Call once from ui_init() after style init. */`,
        `void ui_bindings_init(void);`,
        ``,
        `/** Re-apply current bindings to all bound widgets (called automatically by setters). */`,
        `void ui_bindings_apply(void);`,
        ``,
        `/* Field setters: store the new value and refresh any bound widgets. */`,
        ...setters,
        ``,
        `/* Field getters: return the current value. */`,
        ...getters,
        ``,
        `#ifdef __cplusplus`,
        `} /* extern "C" */`,
        `#endif`,
        ``,
        `#endif /* UI_BINDINGS_H */`,
        ``
    ].join("\n");
}

export function generateBindingsSource(project: EmbfProject): string | null {
    const fields = project.dataModel?.fields ?? [];
    if (fields.length === 0) {
        return null;
    }

    const labelRefs = collectLabelBindings(project);
    const numericRefs = collectNumericBindings(project);
    const definitions: string[] = [];
    const initBody: string[] = [];
    for (const f of fields) {
        if (f.type === "string") {
            definitions.push(`char ${dataVarName(f.id)}[${stringFieldBufSize(f)}];`);
            initBody.push(
                `    strncpy(${dataVarName(f.id)}, ${formatDefault(f)}, sizeof(${dataVarName(f.id)}) - 1);`,
                `    ${dataVarName(f.id)}[sizeof(${dataVarName(f.id)}) - 1] = '\\0';`
            );
        } else {
            const cType = cTypeFor(f);
            const sp = cType.endsWith("*") ? "" : " ";
            definitions.push(`${cType}${sp}${dataVarName(f.id)};`);
            initBody.push(`    ${dataVarName(f.id)} = ${formatDefault(f)};`);
        }
    }

    const applyBody: string[] = [];
    for (const ref of labelRefs) {
        applyBody.push(...emitLabelApply(ref));
    }
    for (const ref of numericRefs) {
        applyBody.push(...emitNumericApply(ref));
    }

    const setterImpls: string[] = [];
    for (const f of fields) {
        if (f.type === "string") {
            setterImpls.push(
                `void ${dataSetterName(f.id)}(const char *value)`,
                `{`,
                `    if (value == NULL) value = "";`,
                `    strncpy(${dataVarName(f.id)}, value, sizeof(${dataVarName(f.id)}) - 1);`,
                `    ${dataVarName(f.id)}[sizeof(${dataVarName(f.id)}) - 1] = '\\0';`,
                `    ui_bindings_apply();`,
                `}`,
                ``
            );
        } else {
            const cType = cTypeFor(f);
            const sp = cType.endsWith("*") ? "" : " ";
            setterImpls.push(
                `void ${dataSetterName(f.id)}(${cType}${sp}value)`,
                `{`,
                `    ${dataVarName(f.id)} = value;`,
                `    ui_bindings_apply();`,
                `}`,
                ``
            );
        }
    }
    const getterImpls: string[] = [];
    for (const f of fields) {
        if (f.type === "string") {
            getterImpls.push(
                `const char *${dataGetterName(f.id)}(void)`,
                `{`,
                `    return ${dataVarName(f.id)};`,
                `}`,
                ``
            );
        } else {
            const cType = cTypeFor(f);
            const sp = cType.endsWith("*") ? "" : " ";
            getterImpls.push(
                `${cType}${sp}${dataGetterName(f.id)}(void)`,
                `{`,
                `    return ${dataVarName(f.id)};`,
                `}`,
                ``
            );
        }
    }

    const v9 = project.project.lvglVersion.startsWith("9");
    const invalidateActiveScreen = v9
        ? `    lv_obj_t *scr = lv_screen_active();`
        : `    lv_obj_t *scr = lv_scr_act();`;

    return [
        AUTOGEN_BANNER,
        `#include "ui.h"`,
        `#include "ui_bindings.h"`,
        `#include <stdio.h>`,
        `#include <string.h>`,
        ``,
        `/* Backing storage definitions. */`,
        ...definitions,
        ``,
        `void ui_bindings_init(void)`,
        `{`,
        ...initBody,
        `}`,
        ``,
        `void ui_bindings_apply(void)`,
        `{`,
        ...(applyBody.length > 0 ? applyBody : ["    /* No bound widgets. */"]),
        invalidateActiveScreen,
        `    if (scr != NULL) {`,
        `        lv_obj_invalidate(scr);`,
        `    }`,
        `}`,
        ``,
        ...setterImpls,
        ...getterImpls
    ].join("\n");
}

/** Map widget type → `lv_*_set_value` setter + arg style (with or without `LV_ANIM_OFF`). */
const NUMERIC_SETTERS: Record<NumericBindingRef["widgetType"], { fn: string; anim: boolean }> = {
    slider: { fn: "lv_slider_set_value", anim: true },
    bar:    { fn: "lv_bar_set_value",    anim: true },
    arc:    { fn: "lv_arc_set_value",    anim: false },
    knob:   { fn: "lv_arc_set_value",    anim: false }
};

function emitNumericApply(ref: NumericBindingRef): string[] {
    const vv = widgetVar(ref.pageId, ref.componentId);
    const setter = NUMERIC_SETTERS[ref.widgetType];
    const cast = ref.fieldType === "float" ? "(int32_t)" : "(int32_t)";
    const valueExpr = `${cast}${dataGetterName(ref.fieldId)}()`;
    const call = setter.anim
        ? `${setter.fn}(${vv}, ${valueExpr}, LV_ANIM_OFF);`
        : `${setter.fn}(${vv}, ${valueExpr});`;
    return [
        `    if (${vv} != NULL) {`,
        `        ${call}`,
        `    }`
    ];
}

function emitLabelApply(ref: LabelBindingRef): string[] {
    const vv = widgetVar(ref.pageId, ref.componentId);
    const lines: string[] = [];
    const { format, args, bufSize } = buildFormatArgs(ref);
    lines.push(`    if (${vv} != NULL) {`);
    lines.push(`        char buf[${bufSize}];`);
    lines.push(`        snprintf(buf, sizeof(buf), "${format}"${args.length ? `, ${args.join(", ")}` : ""});`);
    lines.push(`        lv_label_set_text(${vv}, buf);`);
    lines.push(`    }`);
    return lines;
}

function buildFormatArgs(ref: LabelBindingRef): { format: string; args: string[]; bufSize: number } {
    const text = ref.text;
    let format = "";
    const args: string[] = [];
    let i = 0;
    const re = /\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}/g;
    let m: RegExpExecArray | null;
    let estimatedBytes = 0;
    while ((m = re.exec(text)) !== null) {
        const literal = text.slice(i, m.index);
        format += escapeC(literal);
        estimatedBytes += literal.length;
        const fieldId = m[1];
        const def = ref.fieldDefs.get(fieldId);
        const spec = printfSpecFor(def);
        format += spec.format;
        args.push(spec.arg(fieldId));
        estimatedBytes += spec.budget;
        i = m.index + m[0].length;
    }
    const tail = text.slice(i);
    format += escapeC(tail);
    estimatedBytes += tail.length;
    const bufSize = Math.max(32, Math.min(512, Math.ceil((estimatedBytes + 16) / 16) * 16));
    return { format, args, bufSize };
}

interface PrintfSpec {
    format: string;
    arg: (fieldId: string) => string;
    budget: number;
}

function printfSpecFor(field: DataField | undefined): PrintfSpec {
    switch (field?.type) {
        case "string":
            return { format: "%s", arg: id => dataGetterName(id) + "()", budget: 32 };
        case "int":
            return {
                format: "%" + "d",
                arg: id => `(int)${dataGetterName(id)}()`,
                budget: 12
            };
        case "float":
            return {
                format: "%g",
                arg: id => `(double)${dataGetterName(id)}()`,
                budget: 16
            };
        case "bool":
            return {
                format: "%s",
                arg: id => `(${dataGetterName(id)}() ? "true" : "false")`,
                budget: 6
            };
        default:
            return { format: "%s", arg: id => dataGetterName(id) + "()", budget: 32 };
    }
}

function escapeC(s: string): string {
    return s
        .replace(/\\/g, "\\\\")
        .replace(/"/g, '\\"')
        .replace(/\n/g, "\\n")
        .replace(/\r/g, "\\r")
        .replace(/\t/g, "\\t");
}

/** Initialise backing storage — call after all screens are created, before the first load. */
export function bindingsInitOnlyCalls(project: EmbfProject): string[] {
    if (!project.dataModel?.fields?.length) {
        return [];
    }
    return [`    ui_bindings_init();`];
}

/** Push bound values to widgets — call after `lv_screen_load` so labels/widgets refresh. */
export function bindingsApplyCall(project: EmbfProject): string | null {
    if (!project.dataModel?.fields?.length) {
        return null;
    }
    return `    ui_bindings_apply();`;
}

/** @deprecated Use {@link bindingsInitOnlyCalls} + {@link bindingsApplyCall} in ui_init. */
export function bindingsInitCalls(project: EmbfProject): string[] {
    const init = bindingsInitOnlyCalls(project);
    const apply = bindingsApplyCall(project);
    if (init.length === 0) {
        return [];
    }
    return apply
        ? [...init, `    /* Apply initial values after every screen is created. */`, apply]
        : init;
}

/** Page navigation may need to re-apply bindings; expose the source list separately. */
export function pageHeaderIncludesBindings(project: EmbfProject): string[] {
    return project.dataModel?.fields?.length ? [`#include "ui_bindings.h"`] : [];
}
