import type { EmbfProject, FontDef } from "../types/embf";
import { lvglIncludeDirective } from "./lvglInclude";

const AUTOGEN_BANNER = `/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */
`;

/** Sanitised macro suffix from a FontDef id (e.g. "title 1" → "TITLE_1"). */
export function fontMacroSuffix(id: string): string {
    const cleaned = id
        .trim()
        .replace(/[^a-zA-Z0-9_]+/g, "_")
        .replace(/^_+|_+$/g, "")
        .toUpperCase();
    return cleaned || "FONT";
}

/** True if the font's `name` is one of LVGL's built-in `lv_font_montserrat_*` symbols. */
function isBuiltinMontserrat(name: string): boolean {
    return /^lv_font_montserrat_\d+$/.test(name);
}

/** ui_fonts.h header content — empty array when no fonts are declared. */
export function generateFontsHeader(project: EmbfProject): string | null {
    const fonts = project.fonts ?? [];
    if (fonts.length === 0) {
        return null;
    }

    const declares = fonts
        .filter(f => f.name)
        .map(f => `LV_FONT_DECLARE(${f.name});`);

    const macros = fonts.map(f => {
        const suffix = fontMacroSuffix(f.id);
        return [
            `/** ${f.id}${f.size ? ` (${f.size}px)` : ""} -> ${f.name} */`,
            `#define UI_FONT_${suffix} (&${f.name})`
        ].join("\n");
    });

    return [
        AUTOGEN_BANNER,
        `#ifndef UI_FONTS_H`,
        `#define UI_FONTS_H`,
        ``,
        `#ifdef __cplusplus`,
        `extern "C" {`,
        `#endif`,
        ``,
        lvglIncludeDirective(project),
        ``,
        `/* Forward declarations — fonts not built into LVGL must be compiled into your project. */`,
        ...declares,
        ``,
        `/* Convenience macros (use as the text_font style value or with lv_obj_set_style_text_font). */`,
        ...macros,
        ``,
        `#ifdef __cplusplus`,
        `} /* extern "C" */`,
        `#endif`,
        ``,
        `#endif /* UI_FONTS_H */`,
        ``
    ].join("\n");
}

/** ui_fonts.c source content; only includes the header so the symbols resolve at link time. */
export function generateFontsSource(project: EmbfProject): string | null {
    const fonts = project.fonts ?? [];
    if (fonts.length === 0) {
        return null;
    }

    const customFonts = fonts.filter(f => f.name && !isBuiltinMontserrat(f.name));
    const noteLines = customFonts.length
        ? [
              `/*`,
              ` * Custom font sources to compile into your project:`,
              ...customFonts.map(
                  f => ` *   - ${f.name}${f.source ? ` (${f.source})` : ""}`
              ),
              ` */`
          ]
        : [`/* All fonts are LVGL built-ins; ensure LV_FONT_MONTSERRAT_<n> macros are enabled in lv_conf.h. */`];

    return [AUTOGEN_BANNER, `#include "ui_fonts.h"`, ``, ...noteLines, ``].join("\n");
}

/** Project-level font references for sanity diagnostics (unused entries get reported by callers). */
export function collectReferencedFontFamilies(project: EmbfProject): Set<string> {
    const ids = new Set<string>();
    for (const page of project.pages) {
        function walk(comps: { styles?: { fontFamily?: string }; children?: any[] }[]): void {
            for (const c of comps) {
                const ff = c.styles?.fontFamily;
                if (typeof ff === "string" && ff.trim()) {
                    ids.add(ff.trim());
                }
                if (Array.isArray(c.children)) {
                    walk(c.children);
                }
            }
        }
        walk(page.components as any);
    }
    return ids;
}

/** Used by other codegen to refer to a font by FontDef id (returns null if not declared). */
export function fontExpressionForId(fonts: FontDef[] | undefined, id: string | undefined): string | null {
    if (!id || !fonts) {
        return null;
    }
    const def = fonts.find(f => f.id === id);
    if (!def?.name) {
        return null;
    }
    return `&${def.name}`;
}
