import type { EmbfProject } from "../types/embf";
import { screenLoadAnimCConstant, normalizeScreenLoadAnim } from "./screenLoadAnim";
import { screenInitFn, screenVar } from "./naming";

const AUTOGEN_BANNER = `/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 */
`;

const STACK_MAX = 16;

function emitNavLoadBody(project: EmbfProject, v9: boolean, indent: string): string[] {
    const loadAnim = v9 ? "lv_screen_load_anim" : "lv_scr_load_anim";
    const lines: string[] = [];
    for (const page of project.pages) {
        const scr = screenVar(page.id);
        const init = screenInitFn(page.id);
        lines.push(`${indent}if (strcmp(page_id, "${page.id}") == 0) {`);
        lines.push(`${indent}    if (${scr} == NULL) { ${init}(); }`);
        lines.push(`${indent}    ${loadAnim}(${scr}, anim, time, delay, auto_del);`);
        lines.push(`${indent}    ui_nav_current_page = "${page.id}";`);
        if ((project.dataModel?.fields?.length ?? 0) > 0) {
            lines.push(`${indent}    ui_bindings_apply();`);
        }
        lines.push(`${indent}    return;`);
        lines.push(`${indent}}`);
    }
    lines.push(`${indent}(void)page_id;`);
    return lines;
}

export function generateNavStackHeader(): string {
    return [
        AUTOGEN_BANNER,
        `#ifndef UI_NAV_H`,
        `#define UI_NAV_H`,
        ``,
        `#ifdef __cplusplus`,
        `extern "C" {`,
        `#endif`,
        ``,
        `#include "lvgl.h"`,
        ``,
        `#define UI_NAV_STACK_MAX ${STACK_MAX}`,
        ``,
        `extern const char *ui_nav_current_page;`,
        ``,
        `void ui_nav_load(const char *page_id, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del);`,
        `void ui_nav_push(const char *page_id, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del);`,
        `void ui_nav_pop(lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del);`,
        `void ui_nav_replace(const char *page_id, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del);`,
        `void ui_nav_reset(const char *page_id, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del);`,
        ``,
        `#ifdef __cplusplus`,
        `} /* extern "C" */`,
        `#endif`,
        ``,
        `#endif /* UI_NAV_H */`,
        ``
    ].join("\n");
}

export function generateNavStackSource(project: EmbfProject, v9: boolean): string {
    const loadBody = emitNavLoadBody(project, v9, "    ");

    return [
        AUTOGEN_BANNER,
        `#include "ui_nav.h"`,
        `#include "ui.h"`,
        `#include <string.h>`,
        ``,
        `static const char *ui_nav_stack[UI_NAV_STACK_MAX];`,
        `static uint8_t ui_nav_stack_depth;`,
        `const char *ui_nav_current_page;`,
        ``,
        `void ui_nav_load(const char *page_id, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del)`,
        `{`,
        ...loadBody,
        `}`,
        ``,
        `void ui_nav_push(const char *page_id, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del)`,
        `{`,
        `    if (ui_nav_current_page && ui_nav_stack_depth < UI_NAV_STACK_MAX) {`,
        `        ui_nav_stack[ui_nav_stack_depth++] = ui_nav_current_page;`,
        `    }`,
        `    ui_nav_load(page_id, anim, time, delay, auto_del);`,
        `}`,
        ``,
        `void ui_nav_pop(lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del)`,
        `{`,
        `    if (ui_nav_stack_depth == 0) { return; }`,
        `    const char *prev = ui_nav_stack[--ui_nav_stack_depth];`,
        `    ui_nav_load(prev, anim, time, delay, auto_del);`,
        `}`,
        ``,
        `void ui_nav_replace(const char *page_id, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del)`,
        `{`,
        `    ui_nav_load(page_id, anim, time, delay, auto_del);`,
        `}`,
        ``,
        `void ui_nav_reset(const char *page_id, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay, bool auto_del)`,
        `{`,
        `    ui_nav_stack_depth = 0;`,
        `    ui_nav_load(page_id, anim, time, delay, auto_del);`,
        `}`,
        ``
    ].join("\n");
}

/** Emit nav_push / pop / replace / reset as ui_nav_* calls. */
export function emitNavStackAction(
    action: { type: string; route?: string; anim?: string; time?: number; delay?: number; autoDel?: boolean },
    v9: boolean
): string {
    const time = Math.max(0, Math.round(action.time ?? 300));
    const delay = Math.max(0, Math.round(action.delay ?? 0));
    const autoDel = action.autoDel ? "true" : "false";
    const anim = screenLoadAnimCConstant(normalizeScreenLoadAnim(action.anim) ?? "none", v9);
    switch (action.type) {
        case "nav_push":
            return `ui_nav_push("${action.route ?? ""}", ${anim}, ${time}U, ${delay}U, ${autoDel});`;
        case "nav_pop":
            return `ui_nav_pop(${anim}, ${time}U, ${delay}U, ${autoDel});`;
        case "nav_replace":
            return `ui_nav_replace("${action.route ?? ""}", ${anim}, ${time}U, ${delay}U, ${autoDel});`;
        case "nav_reset":
            return `ui_nav_reset("${action.route ?? ""}", ${anim}, ${time}U, ${delay}U, ${autoDel});`;
        default:
            return `/* unknown nav stack action */`;
    }
}

/** True when any page event uses stack navigation actions. */
export function projectUsesNavStack(project: EmbfProject): boolean {
    for (const page of project.pages) {
        const walk = (comps: typeof page.components): boolean => {
            for (const c of comps) {
                for (const evt of c.events ?? []) {
                    for (const a of evt.actions ?? []) {
                        if (a.type === "nav_push" || a.type === "nav_pop" || a.type === "nav_replace" || a.type === "nav_reset") {
                            return true;
                        }
                    }
                }
                const ch = (c as { children?: typeof page.components }).children;
                if (ch?.length && walk(ch)) {
                    return true;
                }
            }
            return false;
        };
        if (walk(page.components)) {
            return true;
        }
    }
    return false;
}
