import type { EmbfProject, Page } from "../types/embf";
import { screenVar, screenInitFn, headerGuard, widgetVar } from "./naming";
import { emitComponent } from "./widgetGen";

const AUTOGEN_BANNER = `/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */
`;

/** True for LVGL v9.x, false for v8.x */
function isV9(project: EmbfProject): boolean {
    return project.project.lvglVersion.startsWith("9");
}

// ─────────────────────────────────────────────────────────────────────────────
// Per-page header: ui_<page_id>.h
// ─────────────────────────────────────────────────────────────────────────────

export function generatePageHeader(project: EmbfProject, page: Page): string {
    const guard  = headerGuard(page.id);
    const initFn = screenInitFn(page.id);
    const scrVar = screenVar(page.id);

    // Forward-declare all widget variables so other files can reference them
    const widgetExterns = flatWidgets(page).map(w =>
        `extern lv_obj_t *${widgetVar(page.id, w.id)};`
    );

    return [
        AUTOGEN_BANNER,
        `#ifndef ${guard}`,
        `#define ${guard}`,
        ``,
        `#ifdef __cplusplus`,
        `extern "C" {`,
        `#endif`,
        ``,
        `#include "lvgl/lvgl.h"`,
        ``,
        `/** Screen object for page "${page.name}" */`,
        `extern lv_obj_t *${scrVar};`,
        ``,
        widgetExterns.length > 0 ? `/* Widget objects */` : "",
        ...widgetExterns,
        ``,
        `/** Create all widgets for the "${page.name}" screen. */`,
        `void ${initFn}(void);`,
        ``,
        `#ifdef __cplusplus`,
        `} /* extern "C" */`,
        `#endif`,
        ``,
        `#endif /* ${guard} */`,
        ``
    ].filter(l => l !== undefined).join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Per-page source: ui_<page_id>.c
// ─────────────────────────────────────────────────────────────────────────────

export function generatePageSource(project: EmbfProject, page: Page): string {
    const scrVar = screenVar(page.id);
    const initFn = screenInitFn(page.id);
    const v9     = isV9(project);

    // Global variable declarations for this page
    const allWidgets = flatWidgets(page);
    const varDecls = allWidgets.map(w =>
        `lv_obj_t *${widgetVar(page.id, w.id)} = NULL;`
    );

    // Widget creation code
    const bodyLines: string[] = [];
    for (const comp of page.components) {
        bodyLines.push(...emitComponent(page.id, comp, scrVar, v9));
    }

    // Screen background color
    const bgLines: string[] = [];
    if (page.backgroundColor) {
        bgLines.push(
            `    lv_obj_set_style_bg_color(${scrVar}, lv_color_hex(0x${hexToRaw(page.backgroundColor)}), LV_PART_MAIN | LV_STATE_DEFAULT);`,
            `    lv_obj_set_style_bg_opa(${scrVar}, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);`
        );
    }

    return [
        AUTOGEN_BANNER,
        `#include "ui_${page.id}.h"`,
        ``,
        `/* Screen variable */`,
        `lv_obj_t *${scrVar} = NULL;`,
        ``,
        allWidgets.length > 0 ? `/* Widget variables */` : "",
        ...varDecls,
        ``,
        `void ${initFn}(void)`,
        `{`,
        `    ${scrVar} = lv_obj_create(NULL);`,
        ...bgLines,
        ``,
        ...bodyLines,
        `}`,
        ``
    ].filter(l => l !== undefined).join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Root files
// ─────────────────────────────────────────────────────────────────────────────

export function generateRootHeader(project: EmbfProject): string {
    const includes = project.pages.map(p =>
        `#include "ui_${p.id}.h"`
    );

    return [
        AUTOGEN_BANNER,
        `#ifndef UI_H`,
        `#define UI_H`,
        ``,
        `#ifdef __cplusplus`,
        `extern "C" {`,
        `#endif`,
        ``,
        `#include "lvgl/lvgl.h"`,
        ``,
        ...includes,
        ``,
        `/**`,
        ` * Initialise the UI: apply theme, create the first screen, load it.`,
        ` * Call once after lv_init() and your display driver initialisation.`,
        ` */`,
        `void ui_init(void);`,
        ``,
        `#ifdef __cplusplus`,
        `} /* extern "C" */`,
        `#endif`,
        ``,
        `#endif /* UI_H */`,
        ``
    ].join("\n");
}

export function generateRootSource(project: EmbfProject): string {
    const v9          = isV9(project);
    const dark        = project.theme?.dark ? "true" : "false";
    const primaryHex  = project.theme?.primaryColor  ? hexToRaw(project.theme.primaryColor)  : "2196F3";
    const secondaryHex = project.theme?.secondaryColor ? hexToRaw(project.theme.secondaryColor) : "0D47A1";

    // All screen init calls
    const initCalls = project.pages.map(p =>
        `    ${screenInitFn(p.id)}();`
    );

    // Load the first screen
    const firstScreen = project.pages[0];
    const loadCall = v9
        ? `    lv_screen_load(${screenVar(firstScreen.id)});`
        : `    lv_scr_load(${screenVar(firstScreen.id)});`;

    const themeInit = v9
        ? [
            `    lv_theme_t *theme = lv_theme_default_init(`,
            `        lv_display_get_default(),`,
            `        lv_color_hex(0x${primaryHex}),`,
            `        lv_color_hex(0x${secondaryHex}),`,
            `        ${dark},`,
            `        LV_FONT_DEFAULT`,
            `    );`,
            `    lv_display_set_theme(lv_display_get_default(), theme);`
          ]
        : [
            `    lv_theme_t *theme = lv_theme_default_init(`,
            `        lv_color_hex(0x${primaryHex}),`,
            `        lv_color_hex(0x${secondaryHex}),`,
            `        ${dark},`,
            `        LV_FONT_DEFAULT`,
            `    );`,
            `    lv_disp_set_theme(lv_disp_get_default(), theme);`
          ];

    return [
        AUTOGEN_BANNER,
        `#include "ui.h"`,
        ``,
        `void ui_init(void)`,
        `{`,
        ...themeInit,
        ``,
        `    /* Create all screens */`,
        ...initCalls,
        ``,
        `    /* Load initial screen */`,
        loadCall,
        `}`,
        ``
    ].join("\n");
}

export function generateLvConf(project: EmbfProject): string {
    const { bitDepth, colorFormat } = project.display;
    const colorDepth = bitDepth === 16 ? 16 : bitDepth === 24 ? 24 : 32;

    return [
        AUTOGEN_BANNER,
        `/* clang-format off */`,
        `#if 1`,
        ``,
        `#ifndef LV_CONF_H`,
        `#define LV_CONF_H`,
        ``,
        `#include <stdint.h>`,
        ``,
        `/* Color depth — matches project display.bitDepth */`,
        `#define LV_COLOR_DEPTH ${colorDepth}`,
        ``,
        `/* Memory */`,
        `#define LV_USE_STDLIB_MALLOC  LV_STDLIB_BUILTIN`,
        `#define LV_MEM_SIZE           (256U * 1024U)`,
        ``,
        `/* HAL */`,
        `#define LV_DEF_REFR_PERIOD  33`,
        `#define LV_DPI_DEF          ${project.display.dpi ?? 130}`,
        ``,
        `/* OS */`,
        `#define LV_USE_OS   LV_OS_NONE`,
        ``,
        `/* Rendering */`,
        `#define LV_USE_DRAW_SW  1`,
        ``,
        `/* Widgets used in this project — enable as needed */`,
        `#define LV_USE_LABEL        1`,
        `#define LV_USE_BUTTON       1`,
        `#define LV_USE_IMAGE        1`,
        `#define LV_USE_ARC          1`,
        `#define LV_USE_BAR          1`,
        `#define LV_USE_SLIDER       1`,
        `#define LV_USE_SWITCH       1`,
        `#define LV_USE_CHECKBOX     1`,
        `#define LV_USE_SPINNER      1`,
        `#define LV_USE_DROPDOWN     1`,
        `#define LV_USE_ROLLER       1`,
        `#define LV_USE_TEXTAREA     1`,
        `#define LV_USE_LINE         1`,
        `#define LV_USE_BUTTONMATRIX 1`,
        ``,
        `/* Fonts */`,
        `#define LV_FONT_MONTSERRAT_12  1`,
        `#define LV_FONT_MONTSERRAT_14  1`,
        `#define LV_FONT_MONTSERRAT_16  1`,
        `#define LV_FONT_MONTSERRAT_20  1`,
        `#define LV_FONT_MONTSERRAT_24  1`,
        `#define LV_FONT_MONTSERRAT_32  1`,
        `#define LV_FONT_MONTSERRAT_48  1`,
        `#define LV_FONT_DEFAULT        &lv_font_montserrat_14`,
        ``,
        `/* Theme */`,
        `#define LV_USE_THEME_DEFAULT  1`,
        `#define LV_USE_FLEX           1`,
        `#define LV_USE_GRID           1`,
        ``,
        `#define LV_USE_LOG  0`,
        `#define LV_USE_ASSERT_NULL    1`,
        `#define LV_USE_ASSERT_MALLOC  1`,
        ``,
        `#endif /* LV_CONF_H */`,
        `#endif /* enable */`,
        ``
    ].join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Flatten nested widget children into a single list for extern declarations. */
function flatWidgets(page: Page): Array<{ id: string }> {
    const result: Array<{ id: string }> = [];
    function walk(comps: any[]): void {
        for (const c of comps) {
            result.push({ id: c.id });
            if (c.children) walk(c.children);
        }
    }
    walk(page.components);
    return result;
}

/** Strip leading # and return raw 6-char hex, uppercase. */
function hexToRaw(hex: string): string {
    const h = hex.replace("#", "").toUpperCase();
    if (h.length === 3) {
        return h[0]+h[0]+h[1]+h[1]+h[2]+h[2];
    }
    return h.slice(0, 6).padStart(6, "0");
}
