import type { EmbfProject, Page } from "../types/embf";
import { getEffectiveDisplaySize } from "../embfParser";
import { screenVar, screenInitFn, headerGuard, widgetVar } from "./naming";
import { emitComponent } from "./widgetGen";
import { collectPageEvents } from "./eventGen";
import { collectPageSwipes } from "./swipeGen";
import { collectPageGridDescriptors } from "./layoutGen";
import { emitPageInitBaseDir, lvConfRtlCommentBlock } from "./directionGen";
import { projectNeedsRtl } from "../i18n/textDirection";
import { lvglIncludeDirective } from "./lvglInclude";
import { generateImageExternLines } from "../resources/imageCodegen";
import { emitOpacityHelperLines, anyOpacityAnimation } from "./animationGen";
import { bindingsApplyCall, bindingsInitOnlyCalls } from "./bindingsGen";

const AUTOGEN_BANNER = `/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */
`;

/** True for LVGL v9.x, false for v8.x */
export function isLvglV9(project: EmbfProject): boolean {
    return project.project.lvglVersion.startsWith("9");
}

function lvglTargetBanner(project: EmbfProject): string {
    return `/* Target LVGL ${project.project.lvglVersion} — project.lvglVersion in .embf must match the LVGL library linked in your firmware. */`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Per-page header: ui_<page_id>.h
// ─────────────────────────────────────────────────────────────────────────────

export function generatePageHeader(project: EmbfProject, page: Page): string {
    const guard  = headerGuard(page.id);
    const initFn = screenInitFn(page.id);
    const scrVar = screenVar(page.id);

    const widgetExterns = flatWidgets(page).map(w =>
        `extern lv_obj_t *${widgetVar(page.id, w.id)};`
    );

    return [
        AUTOGEN_BANNER,
        `#ifndef ${guard}`,
        `#define ${guard}`,
        ``,
        `#ifdef __cplusplus`,
        `extern "C" {`,
        `#endif`,
        ``,
        lvglIncludeDirective(project),
        ``,
        `/** Screen object for page "${page.name}" */`,
        `extern lv_obj_t *${scrVar};`,
        ``,
        widgetExterns.length > 0 ? `/* Widget objects */` : "",
        ...widgetExterns,
        ``,
        `/** Create all widgets for the "${page.name}" screen. */`,
        `void ${initFn}(void);`,
        ``,
        `#ifdef __cplusplus`,
        `} /* extern "C" */`,
        `#endif`,
        ``,
        `#endif /* ${guard} */`,
        ``
    ].filter(l => l !== undefined).join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Per-page source: ui_<page_id>.c
// ─────────────────────────────────────────────────────────────────────────────

export function generatePageSource(
    project: EmbfProject,
    page: Page,
    opts?: { stringsApi?: boolean; textDirection?: boolean }
): string {
    const scrVar = screenVar(page.id);
    const initFn = screenInitFn(page.id);
    const v9     = isLvglV9(project);
    const stringsApi = opts?.stringsApi === true;
    const textDirection = opts?.textDirection === true;

    const gridStatics = collectPageGridDescriptors(page.id, page.components);
    const allWidgets = flatWidgets(page);
    const varDecls = allWidgets.map(w =>
        `lv_obj_t *${widgetVar(page.id, w.id)} = NULL;`
    );

    const widgetCtx = { fonts: project.fonts, styles: project.styles, stringsApi };
    const bodyLines: string[] = [];
    for (const comp of page.components) {
        bodyLines.push(...emitComponent(page.id, comp, scrVar, v9, widgetCtx));
    }

    const needsOpaHelper = anyOpacityAnimation(page.components as any[]);
    const opaHelper = needsOpaHelper ? emitOpacityHelperLines() : [];

    // Screen background color
    const bgLines: string[] = [];
    if (page.backgroundColor) {
        bgLines.push(
            `    lv_obj_set_style_bg_color(${scrVar}, lv_color_hex(0x${hexToRaw(page.backgroundColor)}), LV_PART_MAIN | LV_STATE_DEFAULT);`,
            `    lv_obj_set_style_bg_opa(${scrVar}, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);`
        );
    }

    // Page scroll enable/disable (optional)
    const scrollLines: string[] = [];
    if ((page as any).scrollX !== undefined || (page as any).scrollY !== undefined) {
        const sx = (page as any).scrollX === true;
        const sy = (page as any).scrollY === true;
        if (!sx && !sy) {
            scrollLines.push(`    lv_obj_clear_flag(${scrVar}, LV_OBJ_FLAG_SCROLLABLE);`);
            scrollLines.push(`    lv_obj_set_scroll_dir(${scrVar}, LV_DIR_NONE);`);
        } else {
            const dirs: string[] = [];
            if (sx) dirs.push("LV_DIR_HOR");
            if (sy) dirs.push("LV_DIR_VER");
            scrollLines.push(`    lv_obj_add_flag(${scrVar}, LV_OBJ_FLAG_SCROLLABLE);`);
            scrollLines.push(`    lv_obj_set_scroll_dir(${scrVar}, ${dirs.join(" | ")});`);
        }
    }

    // Event callbacks and page swipe handlers
    const events = collectPageEvents(project, page, stringsApi);
    const swipes = collectPageSwipes(project, page);
    const decls = [...events.decls, ...swipes.decls];
    const impls = [...events.impls, ...swipes.impls];
    const registrations = [...events.registrations, ...swipes.registrations];

    return [
        AUTOGEN_BANNER,
        `/* ui.h includes every ui_<page>.h so navigate handlers can reference other screens. */`,
        `#include "ui.h"`,
        ``,
        ...(gridStatics.length > 0 ? [`/* Grid track descriptors */`, ...gridStatics, ``] : []),
        `/* Screen variable */`,
        `lv_obj_t *${scrVar} = NULL;`,
        ``,
        allWidgets.length > 0 ? `/* Widget variables */` : "",
        ...varDecls,
        ``,
        decls.length > 0 ? `/* Event callback forward declarations */` : "",
        ...decls,
        ``,
        decls.length > 0 ? `/* Event callback implementations */` : "",
        ...impls.map(fn => fn + "\n"),
        ...opaHelper,
        `void ${initFn}(void)`,
        `{`,
        `    ${scrVar} = lv_obj_create(NULL);`,
        ...(textDirection ? [emitPageInitBaseDir(scrVar)] : []),
        ...bgLines,
        ...scrollLines,
        ``,
        ...bodyLines,
        registrations.length > 0 ? `    /* Event registrations */` : "",
        ...registrations,
        `}`,
        ``
    ].filter(l => l !== undefined).join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Display resolution (matches EmbeddedFlow preview)
// ─────────────────────────────────────────────────────────────────────────────

/** Defines horizontal/vertical resolution after applying `display.orientation` to JSON width/height. */
export function generateDisplayHeader(project: EmbfProject): string {
    const { width: hor, height: ver } = getEffectiveDisplaySize(project);
    const { width: jsonW, height: jsonH, orientation } = project.display;

    return [
        AUTOGEN_BANNER,
        `#ifndef UI_DISPLAY_H`,
        `#define UI_DISPLAY_H`,
        ``,
        `/**`,
        ` * Author JSON: width=${jsonW}, height=${jsonH}, orientation=${orientation}`,
        ` * Use EMBF_DISPLAY_* when creating the LVGL display (same logical size as the VS Code preview).`,
        ` */`,
        `#define EMBF_DISPLAY_JSON_WIDTH  (${jsonW}U)`,
        `#define EMBF_DISPLAY_JSON_HEIGHT (${jsonH}U)`,
        `#define EMBF_DISPLAY_HOR_RES     (${hor}U)`,
        `#define EMBF_DISPLAY_VER_RES     (${ver}U)`,
        ``,
        `#endif /* UI_DISPLAY_H */`,
        ``
    ].join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Root files
// ─────────────────────────────────────────────────────────────────────────────

export interface GenerateRootHeaderOptions {
    /** Converted image symbols to declare in `ui.h` (sources are `ui_img_*.c` in this folder). */
    imageSymbols?: { symbolName: string; lvglV9: boolean }[];
    /** When true, `ui.h` will `#include "ui_fonts.h"` so callers get UI_FONT_* macros. */
    includeFonts?: boolean;
    /** When true, `ui.h` will `#include "ui_styles.h"` so callers get extern style decls + `ui_styles_init`. */
    includeStyles?: boolean;
    /** When true, `ui.h` will `#include "ui_bindings.h"` so callers get setters/getters. */
    includeBindings?: boolean;
    /** When true, `ui.h` will `#include "ui_strings.h"` for `ui_get_string()`. */
    includeStrings?: boolean;
    /** When true, `ui.h` will `#include "ui_nav.h"` for stack navigation. */
    includeNav?: boolean;
}

export function generateRootHeader(
    project: EmbfProject,
    opts?: GenerateRootHeaderOptions
): string {
    const includes = project.pages.map(p =>
        `#include "ui_${p.id}.h"`
    );
    const imageLines =
        opts?.imageSymbols && opts.imageSymbols.length > 0
            ? [...generateImageExternLines(opts.imageSymbols), ``]
            : [];
    const fontsInclude    = opts?.includeFonts    ? [`#include "ui_fonts.h"`]    : [];
    const stylesInclude   = opts?.includeStyles   ? [`#include "ui_styles.h"`]   : [];
    const bindingsInclude = opts?.includeBindings ? [`#include "ui_bindings.h"`] : [];
    const stringsInclude  = opts?.includeStrings  ? [`#include "ui_strings.h"`]  : [];
    const navInclude      = opts?.includeNav      ? [`#include "ui_nav.h"`]      : [];

    return [
        AUTOGEN_BANNER,
        `#ifndef UI_H`,
        `#define UI_H`,
        ``,
        `#ifdef __cplusplus`,
        `extern "C" {`,
        `#endif`,
        ``,
        `#include "ui_display.h"`,
        lvglIncludeDirective(project),
        ...fontsInclude,
        ...stylesInclude,
        ...bindingsInclude,
        ...stringsInclude,
        ...navInclude,
        ``,
        ...imageLines,
        ...includes,
        ``,
        `/**`,
        ` * Initialise the UI: apply theme, create the first screen, load it.`,
        ` * Call once after lv_init() and your display driver initialisation.`,
        ` */`,
        `void ui_init(void);`,
        ``,
        `#ifdef __cplusplus`,
        `} /* extern "C" */`,
        `#endif`,
        ``,
        `#endif /* UI_H */`,
        ``
    ].join("\n");
}

export function generateRootSource(project: EmbfProject, opts?: { includeStrings?: boolean }): string {
    const v9          = isLvglV9(project);
    const dark        = project.theme?.dark ? "true" : "false";
    const primaryHex  = project.theme?.primaryColor  ? hexToRaw(project.theme.primaryColor)  : "2196F3";
    const secondaryHex = project.theme?.secondaryColor ? hexToRaw(project.theme.secondaryColor) : "0D47A1";

    // All screen init calls
    const initCalls = project.pages.map(p =>
        `    ${screenInitFn(p.id)}();`
    );

    // Load the first screen
    const firstScreen = project.pages[0];
    const loadCall = v9
        ? `    lv_screen_load(${screenVar(firstScreen.id)});`
        : `    lv_scr_load(${screenVar(firstScreen.id)});`;

    const themeInit = v9
        ? [
            `    lv_theme_t *theme = lv_theme_default_init(`,
            `        lv_display_get_default(),`,
            `        lv_color_hex(0x${primaryHex}),`,
            `        lv_color_hex(0x${secondaryHex}),`,
            `        ${dark},`,
            `        LV_FONT_DEFAULT`,
            `    );`,
            `    lv_display_set_theme(lv_display_get_default(), theme);`
          ]
        : [
            `    lv_theme_t *theme = lv_theme_default_init(`,
            `        lv_disp_get_default(),`,
            `        lv_color_hex(0x${primaryHex}),`,
            `        lv_color_hex(0x${secondaryHex}),`,
            `        ${dark},`,
            `        LV_FONT_DEFAULT`,
            `    );`,
            `    lv_disp_set_theme(lv_disp_get_default(), theme);`
          ];

    const stringsInit =
        opts?.includeStrings === true
            ? [`    /* String resources (strings.res) — default locale + runtime ui_set_locale() */`, `    ui_strings_init();`, ``]
            : [];
    const stylesInit = (project.styles?.length ?? 0) > 0
        ? [`    /* Initialise named lv_style_t objects (ui_styles.c) */`, `    ui_styles_init();`, ``]
        : [];
    const bindingsInit = bindingsInitOnlyCalls(project);
    const bindingsApply = bindingsApplyCall(project);
    const bindingsBlock =
        bindingsInit.length > 0
            ? [`    /* Initialise data bindings (ui_bindings.c) */`, ...bindingsInit, ``]
            : [];
    const bindingsAfterLoad = bindingsApply
        ? [`    /* Apply {{field}} labels and bound widgets on the active screen */`, bindingsApply, ``]
        : [];

    return [
        AUTOGEN_BANNER,
        lvglTargetBanner(project),
        `#include "ui.h"`,
        ``,
        `void ui_init(void)`,
        `{`,
        ...themeInit,
        ``,
        ...stringsInit,
        ...stylesInit,
        `    /* Create all screens */`,
        ...initCalls,
        ``,
        ...bindingsBlock,
        `    /* Load initial screen */`,
        loadCall,
        ``,
        ...bindingsAfterLoad,
        `}`,
        ``
    ].join("\n");
}

export function generateLvConf(
    project: EmbfProject,
    strings?: import("../i18n/stringsResParser").StringsResFile | null
): string {
    const { bitDepth, colorFormat } = project.display;
    const colorDepth = bitDepth === 16 ? 16 : bitDepth === 24 ? 24 : 32;
    const needsRtl = projectNeedsRtl(project, strings ?? null);
    const rtlBlock = needsRtl
        ? [
              `/* Bidirectional + Arabic/Persian shaping (project uses RTL locales) */`,
              `#define LV_USE_BIDI  1`,
              `#define LV_USE_ARABIC_PERSIAN_CHARS  1`,
              `#define LV_FONT_DEJAVU_16_PERSIAN_HEBREW  1`,
              lvConfRtlCommentBlock(),
              ``
          ]
        : [
              `/* RTL/BiDi disabled — enable when using ar/fa/he locales: */`,
              `#define LV_USE_BIDI  0`,
              `#define LV_USE_ARABIC_PERSIAN_CHARS  0`,
              `#define LV_FONT_DEJAVU_16_PERSIAN_HEBREW  0`,
              lvConfRtlCommentBlock(),
              ``
          ];

    return [
        AUTOGEN_BANNER,
        `/* clang-format off */`,
        `#if 1`,
        ``,
        `#ifndef LV_CONF_H`,
        `#define LV_CONF_H`,
        ``,
        `#include <stdint.h>`,
        ``,
        `/* Color depth — matches project display.bitDepth (${colorFormat}) */`,
        `#define LV_COLOR_DEPTH ${colorDepth}`,
        ``,
        `/* Memory */`,
        `#define LV_USE_STDLIB_MALLOC  LV_STDLIB_BUILTIN`,
        `#define LV_MEM_SIZE           (256U * 1024U)`,
        ``,
        `/* HAL */`,
        `#define LV_DEF_REFR_PERIOD  33`,
        `#define LV_DPI_DEF          ${project.display.dpi ?? 130}`,
        ``,
        `/* OS */`,
        `#define LV_USE_OS   LV_OS_NONE`,
        ``,
        `/* Rendering */`,
        `#define LV_USE_DRAW_SW  1`,
        ``,
        `/* Widgets used in this project — enable as needed */`,
        `#define LV_USE_LABEL        1`,
        `#define LV_USE_BUTTON       1`,
        `#define LV_USE_IMAGE        1`,
        `#define LV_USE_ARC          1`,
        `#define LV_USE_BAR          1`,
        `#define LV_USE_SLIDER       1`,
        `#define LV_USE_SWITCH       1`,
        `#define LV_USE_CHECKBOX     1`,
        `#define LV_USE_SPINNER      1`,
        `#define LV_USE_DROPDOWN     1`,
        `#define LV_USE_ROLLER       1`,
        `#define LV_USE_TEXTAREA     1`,
        `#define LV_USE_LINE         1`,
        `#define LV_USE_BUTTONMATRIX 1`,
        ``,
        `/* Fonts */`,
        `#define LV_FONT_MONTSERRAT_12  1`,
        `#define LV_FONT_MONTSERRAT_14  1`,
        `#define LV_FONT_MONTSERRAT_16  1`,
        `#define LV_FONT_MONTSERRAT_20  1`,
        `#define LV_FONT_MONTSERRAT_24  1`,
        `#define LV_FONT_MONTSERRAT_32  1`,
        `#define LV_FONT_MONTSERRAT_48  1`,
        `#define LV_FONT_DEFAULT        &lv_font_montserrat_14`,
        ``,
        `/* Theme */`,
        `#define LV_USE_THEME_DEFAULT  1`,
        `#define LV_USE_FLEX           1`,
        `#define LV_USE_GRID           1`,
        ``,
        ...rtlBlock,
        `#define LV_USE_LOG  0`,
        `#define LV_USE_ASSERT_NULL    1`,
        `#define LV_USE_ASSERT_MALLOC  1`,
        ``,
        `/* Hide FPS / CPU overlay labels on the UI screen */`,
        `#define LV_USE_SYSMON         0`,
        `#define LV_USE_PERF_MONITOR   0`,
        `#define LV_USE_MEM_MONITOR    0`,
        ``,
        `#endif /* LV_CONF_H */`,
        `#endif /* enable */`,
        ``
    ].join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Flatten nested widget children into a single list for extern declarations. */
function flatWidgets(page: Page): Array<{ id: string }> {
    const result: Array<{ id: string }> = [];
    function walk(comps: any[]): void {
        for (const c of comps) {
            result.push({ id: c.id });
            if (c.children) walk(c.children);
        }
    }
    walk(page.components);
    return result;
}

/** Strip leading # and return raw 6-char hex, uppercase. */
function hexToRaw(hex: string): string {
    const h = hex.replace("#", "").toUpperCase();
    if (h.length === 3) {
        return h[0]+h[0]+h[1]+h[1]+h[2]+h[2];
    }
    return h.slice(0, 6).padStart(6, "0");
}
