import * as fs from "fs";
import * as path from "path";
import type { LvglIncludePath } from "../types/embf";
import { resolveLvglIncludePath } from "./lvglInclude";
import type { EmbfProject } from "../types/embf";

const AUTOGEN_BANNER = `/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */
`;

/** Montserrat sizes available in LVGL built-in fonts. */
export const MONTSERRAT_SIZES = [8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48] as const;

/** Latin-1 supplement fonts shipped with EmbeddedFlow (German umlauts, etc.). */
export const LATIN1_FONT_SIZES = [12, 14, 16, 18, 20, 24, 32, 48] as const;

/** Pick nearest built-in Montserrat px size. */
export function nearestMontserratSize(size: number): number {
    return MONTSERRAT_SIZES.reduce((prev, cur) =>
        Math.abs(cur - size) < Math.abs(prev - size) ? cur : prev
    );
}

/** C call: Montserrat at `size` with Latin-1 + DejaVu fallback chain. */
export function uiFontLocalizedCall(size: number): string {
    return `ui_font_montserrat_nearest(${nearestMontserratSize(size)})`;
}

/** @deprecated Prefer {@link uiFontLocalizedCall} for mixed en/de/fa projects. */
export const UI_FONT_BIDI_EXPR = "UI_FONT_BIDI";

const WASM_SRC_DIR = path.join(__dirname, "..", "..", "wasm-src");

/** Set from `extension.ts` activate so packaged VSIX resolves bundled font sources. */
let extensionRootForFonts: string | undefined;

export function setLatin1FontsExtensionRoot(extensionPath: string): void {
    extensionRootForFonts = extensionPath;
}

function resolveLatin1FontDir(): string {
    const candidates: string[] = [];
    if (extensionRootForFonts) {
        candidates.push(path.join(extensionRootForFonts, "wasm-src"));
    }
    candidates.push(WASM_SRC_DIR);
    for (const dir of candidates) {
        if (fs.existsSync(path.join(dir, "embf_font_latin1_12.c"))) {
            return dir;
        }
    }
    return candidates[0] ?? WASM_SRC_DIR;
}

function readLatin1FontFile(size: number): string {
    const dir = resolveLatin1FontDir();
    const filePath = path.join(dir, `embf_font_latin1_${size}.c`);
    if (!fs.existsSync(filePath)) {
        throw new Error(
            `Missing ${path.basename(filePath)} (searched: ${dir}). Reinstall EmbeddedFlow or rebuild the VSIX with npm dependencies included.`
        );
    }
    return fs.readFileSync(filePath, "utf8");
}

const LVGL_FONT_INCLUDE_BLOCK =
    /#ifdef LV_LVGL_H_INCLUDE_SIMPLE\r?\n#include "lvgl\.h"\r?\n#else\r?\n#include "lvgl\/lvgl\.h"\r?\n#endif/;

/** Read an `embf_font_latin1_<size>.c` source file for device codegen output. */
export function readLatin1FontSource(size: number, lvglInclude: LvglIncludePath): string {
    let content = readLatin1FontFile(size);
    content = content.replace(LVGL_FONT_INCLUDE_BLOCK, `#include "${lvglInclude}"`);
    return content;
}

/** @see readLatin1FontSource */
export function readLatin1FontSourceForProject(size: number, project: EmbfProject): string {
    return readLatin1FontSource(size, resolveLvglIncludePath(project));
}

export function generateRtlFontsHeader(): string {
    return [
        AUTOGEN_BANNER,
        `#ifndef UI_RTL_FONTS_H`,
        `#define UI_RTL_FONTS_H`,
        ``,
        `#include "lvgl.h"`,
        `#include <stdint.h>`,
        ``,
        `/* Requires LV_FONT_DEJAVU_16_PERSIAN_HEBREW 1 in lv_conf / sdkconfig. */`,
        `#if LV_FONT_DEJAVU_16_PERSIAN_HEBREW`,
        `#define UI_FONT_BIDI  (&lv_font_dejavu_16_persian_hebrew)`,
        `#else`,
        `#define UI_FONT_BIDI  LV_FONT_DEFAULT`,
        `#endif`,
        ``,
        `/** Wire Montserrat → Latin-1 → DejaVu fallback (call once from ui_init before widgets). */`,
        `void ui_rtl_fonts_init(void);`,
        ``,
        `/** Built-in Montserrat only (no fallbacks). */`,
        `const lv_font_t *ui_font_montserrat_plain(uint8_t size);`,
        ``,
        `/** Montserrat + Latin-1 + DejaVu fallback — use for all localized text. */`,
        `const lv_font_t *ui_font_montserrat_nearest(uint8_t size);`,
        ``,
        `#endif /* UI_RTL_FONTS_H */`,
        ``
    ].join("\n");
}

function montserratGuard(size: number): string {
    return `LV_FONT_MONTSERRAT_${size}`;
}

function montserratSymbol(size: number): string {
    return `lv_font_montserrat_${size}`;
}

function buildPlainSizePicker(): string {
    const sizes = [...MONTSERRAT_SIZES];
    const lines: string[] = [
        `const lv_font_t *ui_font_montserrat_plain(uint8_t size)`,
        `{`,
        `    uint8_t best = 14;`,
        `    uint8_t best_diff = 255;`,
        `    static const uint8_t available[] = { ${sizes.join(", ")} };`,
        `    for (unsigned i = 0; i < sizeof(available) / sizeof(available[0]); i++) {`,
        `        uint8_t d = (size > available[i]) ? (size - available[i]) : (available[i] - size);`,
        `        if (d < best_diff) {`,
        `            best_diff = d;`,
        `            best = available[i];`,
        `        }`,
        `    }`,
        `    switch (best) {`
    ];
    for (const s of sizes) {
        lines.push(`#if ${montserratGuard(s)}`);
        lines.push(`        case ${s}: return &${montserratSymbol(s)};`);
        lines.push(`#endif`);
    }
    lines.push(`        default: break;`);
    lines.push(`    }`);
    lines.push(`    return LV_FONT_DEFAULT;`);
    lines.push(`}`);
    return lines.join("\n");
}

/** Threshold picker matching the WASM preview runtime (22px → 20px wired font, etc.). */
function buildNearestSizePicker(): string {
    const thresholds: { max: number; size: number }[] = [
        { max: 12, size: 12 },
        { max: 15, size: 14 },
        { max: 17, size: 16 },
        { max: 19, size: 18 },
        { max: 22, size: 20 },
        { max: 28, size: 24 },
        { max: 40, size: 32 },
        { max: 255, size: 48 }
    ];
    const lines: string[] = [
        `const lv_font_t *ui_font_montserrat_nearest(uint8_t size)`,
        `{`,
        `#if LV_FONT_DEJAVU_16_PERSIAN_HEBREW`
    ];
    for (const { max, size } of thresholds) {
        lines.push(`#if ${montserratGuard(size)}`);
        lines.push(`    if (size <= ${max}) return &ui_f_ms_${size};`);
        lines.push(`#endif`);
    }
    lines.push(`    return UI_FONT_BIDI;`);
    lines.push(`#else`);
    lines.push(`    return ui_font_montserrat_plain(size);`);
    lines.push(`#endif`);
    lines.push(`}`);
    return lines.join("\n");
}

function buildInitBlock(): string {
    const lines: string[] = [`void ui_rtl_fonts_init(void)`, `{`];
    for (const size of LATIN1_FONT_SIZES) {
        lines.push(`#if ${montserratGuard(size)}`);
        lines.push(`    ui_f_latin_${size} = embf_font_latin1_${size};`);
        lines.push(`    ui_f_latin_${size}.fallback = &lv_font_dejavu_16_persian_hebrew;`);
        lines.push(`    ui_f_ms_${size} = ${montserratSymbol(size)};`);
        lines.push(`    ui_f_ms_${size}.fallback = &ui_f_latin_${size};`);
        lines.push(`#endif`);
    }
    lines.push(`}`);
    return lines.join("\n");
}

export function generateRtlFontsSource(): string {
    const latinExterns = LATIN1_FONT_SIZES.map(
        s => `#if ${montserratGuard(s)}\nextern const lv_font_t embf_font_latin1_${s};\n#endif`
    ).join("\n");

    const latinStatics = LATIN1_FONT_SIZES.map(
        s =>
            `#if ${montserratGuard(s)}\nstatic lv_font_t ui_f_latin_${s};\nstatic lv_font_t ui_f_ms_${s};\n#endif`
    ).join("\n");

    const cmakeNote = LATIN1_FONT_SIZES.map(s => ` *   embf_font_latin1_${s}.c`).join("\n");

    return [
        AUTOGEN_BANNER,
        `#include "ui_rtl_fonts.h"`,
        ``,
        buildPlainSizePicker(),
        ``,
        `#if LV_FONT_DEJAVU_16_PERSIAN_HEBREW`,
        ``,
        latinExterns,
        ``,
        latinStatics,
        ``,
        buildInitBlock(),
        ``,
        buildNearestSizePicker(),
        ``,
        `#else /* LV_FONT_DEJAVU_16_PERSIAN_HEBREW */`,
        ``,
        `void ui_rtl_fonts_init(void)`,
        `{`,
        `}`,
        ``,
        `const lv_font_t *ui_font_montserrat_nearest(uint8_t size)`,
        `{`,
        `    return ui_font_montserrat_plain(size);`,
        `}`,
        ``,
        `#endif`,
        ``,
        `/*`,
        ` * Compile these Latin-1 supplement fonts into your firmware (alongside ui_rtl_fonts.c):`,
        cmakeNote,
        ` * Chain: Montserrat → embf_font_latin1_* (0xC0-0xFF) → lv_font_dejavu_16_persian_hebrew`,
        ` */`,
        ``
    ].join("\n");
}
