import * as fs from "fs";
import type { EmbfProject, WidgetTextValue } from "../types/embf";
import { resolveStringsResPath } from "../i18n/stringsResPath";
import { readStringsResFile, type StringsResFile } from "../i18n/stringsResParser";
import {
    collectStringRefsInProject,
    getWidgetTextRef,
    isStringResourceRef,
    listAllStringKeys
} from "../i18n/widgetText";
import { toIdentifier, widgetVar } from "./naming";
import { uiFontLocalizedCall, nearestMontserratSize } from "./rtlFontsGen";
import { emitDirectionHelpers } from "./directionGen";

const AUTOGEN_BANNER = `/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */
`;

/** C enum token for a string resource key, e.g. `temp_label` → `UI_STR_TEMP_LABEL`. */
export function stringKeyToEnumSymbol(key: string): string {
    return `UI_STR_${toIdentifier(key).toUpperCase()}`;
}

/** Filename suffix for a locale, e.g. `pt-BR` → `pt_BR`. */
export function localeToDefBasename(localeId: string): string {
    return toIdentifier(localeId);
}

/** C macro token selecting a locale at compile time, e.g. `en` → `UI_LOCALE_en`. */
export function localeToSelectMacro(localeId: string): string {
    return `UI_LOCALE_${localeToDefBasename(localeId)}`;
}

/** Per-locale X-Macro list name — unique so multiple `.def` files can be included in one `.c`. */
export function localeToStringListMacro(localeId: string): string {
    return `UI_STRING_LIST_${localeToDefBasename(localeId).toUpperCase()}`;
}

function escapeCString(text: string): string {
    return text
        .replace(/\\/g, "\\\\")
        .replace(/"/g, '\\"')
        .replace(/\n/g, "\\n")
        .replace(/\r/g, "\\r")
        .replace(/\t/g, "\\t");
}

function walkActions(project: EmbfProject, fn: (text: WidgetTextValue | undefined, path: string) => void): void {
    for (const page of project.pages) {
        walkComponents(page.components, (c, base) => {
            for (const evt of c.events ?? []) {
                for (let i = 0; i < evt.actions.length; i++) {
                    const a = evt.actions[i];
                    if (a.type === "set_text") {
                        fn(a.text, `${base}.events[].actions[${i}].text`);
                    }
                }
            }
        });
    }
}

function walkComponents(
    components: import("../types/embf").Component[],
    fn: (c: import("../types/embf").Component, base: string) => void,
    pageId?: string
): void {
    for (const c of components) {
        const base = pageId ? `pages[${pageId}].${c.id}` : c.id;
        fn(c, base);
        if ("children" in c && Array.isArray((c as { children?: unknown[] }).children)) {
            walkComponents((c as { children: import("../types/embf").Component[] }).children, fn, pageId);
        }
    }
}

/** Union of keys in `.res` and keys referenced by widgets / set_text actions. */
export function collectCodegenStringKeys(project: EmbfProject, strings: StringsResFile | null): string[] {
    const keys = new Set<string>();
    if (strings) {
        for (const k of listAllStringKeys(strings)) {
            keys.add(k);
        }
    }
    for (const r of collectStringRefsInProject(project)) {
        keys.add(r.key);
    }
    walkActions(project, (text, _path) => {
        const ref = getWidgetTextRef(text);
        if (ref) {
            keys.add(ref);
        }
    });
    return [...keys].sort();
}

export function loadStringsResForCodegen(project: EmbfProject, embfPath: string): StringsResFile | null {
    const abs = resolveStringsResPath(project, embfPath);
    if (!fs.existsSync(abs)) {
        return null;
    }
    try {
        return readStringsResFile(abs);
    } catch {
        return null;
    }
}

export interface StringsCodegenResult {
    keys: string[];
    localeIds: string[];
    defaultLocale: string;
    idsHeader: string;
    header: string;
    source: string;
    refreshSource: string;
    localeDefs: Map<string, string>;
}

export interface LocalizedWidgetBinding {
    pageId: string;
    componentId: string;
    kind: "label" | "button" | "checkbox";
    key: string;
    /** Nearest Montserrat px from widget styles (for locale refresh font). */
    fontPx: number;
    /** Label/checkbox text align from widget styles (fixed-layout RTL keeps designer align). */
    textAlignC: string;
}

function lvTextAlignC(align: string | undefined): string {
    switch (align) {
        case "left":
            return "LV_TEXT_ALIGN_LEFT";
        case "center":
            return "LV_TEXT_ALIGN_CENTER";
        case "right":
            return "LV_TEXT_ALIGN_RIGHT";
        default:
            return "LV_TEXT_ALIGN_AUTO";
    }
}

function localizedTextAlign(c: import("../types/embf").Component): string {
    const styles = (c as { styles?: { align?: string } }).styles;
    return lvTextAlignC(styles?.align);
}

function localizedFontPx(c: import("../types/embf").Component): number {
    const styles = (c as { styles?: { fontSize?: number } }).styles;
    return nearestMontserratSize(styles?.fontSize ?? 14);
}

/** Widgets whose text/label uses `{ ref }` — targets for ui_refresh_localized_text(). */
export function collectLocalizedWidgets(project: EmbfProject): LocalizedWidgetBinding[] {
    const out: LocalizedWidgetBinding[] = [];
    for (const page of project.pages) {
        walkComponents(page.components, c => {
            if (c.hidden) {
                return;
            }
            const fontPx = localizedFontPx(c);
            const textAlignC = localizedTextAlign(c);
            if (c.type === "label" && isStringResourceRef(c.text)) {
                out.push({ pageId: page.id, componentId: c.id, kind: "label", key: c.text.ref, fontPx, textAlignC });
            } else if (c.type === "button" && c.label !== undefined && isStringResourceRef(c.label)) {
                out.push({ pageId: page.id, componentId: c.id, kind: "button", key: c.label.ref, fontPx, textAlignC });
            } else if (c.type === "checkbox" && c.text !== undefined && isStringResourceRef(c.text)) {
                out.push({ pageId: page.id, componentId: c.id, kind: "checkbox", key: c.text.ref, fontPx, textAlignC });
            }
        }, page.id);
    }
    return out;
}

function emitRefreshLine(binding: LocalizedWidgetBinding, needsRtl: boolean): string {
    const v = widgetVar(binding.pageId, binding.componentId);
    const expr = `ui_get_string(${stringKeyToEnumSymbol(binding.key)})`;
    switch (binding.kind) {
        case "label":
            return needsRtl
                ? `    if (${v}) { lv_label_set_text(${v}, ${expr}); ui_apply_localized_label_style(${v}, ${binding.fontPx}, ${binding.textAlignC}); }`
                : `    if (${v}) lv_label_set_text(${v}, ${expr});`;
        case "button":
            return `    ui_set_button_label(${v}, ${expr}, ${binding.fontPx});`;
        case "checkbox":
            return needsRtl
                ? `    if (${v}) { lv_checkbox_set_text(${v}, ${expr}); ui_apply_localized_label_style(${v}, ${binding.fontPx}, ${binding.textAlignC}); }`
                : `    if (${v}) lv_checkbox_set_text(${v}, ${expr});`;
    }
}

const LOCALIZED_LABEL_STYLE_HELPER = [
    `/** Text direction on the widget only — screen layout stays LTR (absolute positions). */`,
    `static void ui_apply_localized_label_style(lv_obj_t *obj, uint8_t font_px, lv_text_align_t align_hint)`,
    `{`,
    `    if (obj == NULL) {`,
    `        return;`,
    `    }`,
    `    lv_base_dir_t dir = ui_resolve_base_dir();`,
    `    lv_obj_set_style_base_dir(obj, dir, LV_PART_MAIN);`,
    `    lv_text_align_t align = align_hint;`,
    `    if (align_hint == LV_TEXT_ALIGN_AUTO) {`,
    `        align = (dir == LV_BASE_DIR_RTL) ? LV_TEXT_ALIGN_RIGHT : LV_TEXT_ALIGN_LEFT;`,
    `    }`,
    `    lv_obj_set_style_text_align(obj, align, LV_PART_MAIN);`,
    `    lv_obj_set_style_text_font(obj, ui_font_montserrat_nearest(font_px), LV_PART_MAIN);`,
    `    if (lv_obj_check_type(obj, &lv_label_class)) {`,
    `        lv_label_set_long_mode(obj, LV_LABEL_LONG_WRAP);`,
    `    }`,
    `}`,
    ``,
    `static void ui_apply_localized_button_label_style(lv_obj_t *child, uint8_t font_px)`,
    `{`,
    `    if (child == NULL) {`,
    `        return;`,
    `    }`,
    `    lv_base_dir_t dir = ui_resolve_base_dir();`,
    `    lv_obj_set_style_base_dir(child, dir, LV_PART_MAIN);`,
    `    lv_obj_set_style_text_font(child, ui_font_montserrat_nearest(font_px), LV_PART_MAIN);`,
    `}`,
    ``
].join("\n");

function buildButtonLabelHelper(needsRtl: boolean): string {
    const styleLine = needsRtl
        ? `            ui_apply_localized_button_label_style(child, font_px);`
        : "";
    return [
        `/** Button labels are created as child lv_label objects in page init (not file-scope globals). */`,
        `static void ui_set_button_label(lv_obj_t *btn, const char *text, uint8_t font_px)`,
        `{`,
        `    if (btn == NULL || text == NULL) {`,
        `        return;`,
        `    }`,
        `    const uint32_t n = lv_obj_get_child_cnt(btn);`,
        `    for (uint32_t i = 0; i < n; i++) {`,
        `        lv_obj_t *child = lv_obj_get_child(btn, i);`,
        `        if (child != NULL && lv_obj_check_type(child, &lv_label_class)) {`,
        `            lv_label_set_text(child, text);`,
        styleLine,
        `            lv_obj_center(child);`,
        `            return;`,
        `        }`,
        `    }`,
        `}`,
        ``
    ].filter(l => l !== "").join("\n");
}

export function generateStringsCodegen(
    project: EmbfProject,
    strings: StringsResFile | null,
    needsRtl = false
): StringsCodegenResult | null {
    const keys = collectCodegenStringKeys(project, strings);
    if (!keys.length) {
        return null;
    }

    const defaultLocale = strings?.defaultLocale ?? "en";
    const locales =
        strings ??
        ({
            defaultLocale,
            locales: { [defaultLocale]: Object.fromEntries(keys.map(k => [k, k])) }
        } satisfies StringsResFile);

    const keyLines = keys.map(k => `    X(${stringKeyToEnumSymbol(k)})`).join(" \\\n");

    const idsHeader = [
        AUTOGEN_BANNER,
        `#ifndef UI_STRINGS_IDS_H`,
        `#define UI_STRINGS_IDS_H`,
        ``,
        `#define UI_STRING_KEYS \\`,
        keyLines,
        ``,
        `#endif /* UI_STRINGS_IDS_H */`,
        ``
    ].join("\n");

    const header = [
        AUTOGEN_BANNER,
        `#ifndef UI_STRINGS_H`,
        `#define UI_STRINGS_H`,
        ``,
        `#include "lvgl.h"`,
        `#include "ui_strings_ids.h"`,
        ``,
        `typedef enum {`,
        `#define X(id) id,`,
        `    UI_STRING_KEYS`,
        `#undef X`,
        `    UI_STR_COUNT`,
        `} ui_string_id_t;`,
        ``,
        `const char *ui_get_string(ui_string_id_t id);`,
        ``,
        `/** Select active locale at runtime (must match a locale id in strings.res). */`,
        `void ui_set_locale(const char *locale_id);`,
        ``,
        `/** Current locale id, or "" if unknown. */`,
        `const char *ui_get_active_locale(void);`,
        ``,
        `/** Re-apply ui_get_string() on every widget that references a string resource key. */`,
        `void ui_refresh_localized_text(void);`,
        ...(needsRtl
            ? [
                  ``,
                  `/** Resolve base text direction for the active locale (RTL6). */`,
                  `lv_base_dir_t ui_resolve_base_dir(void);`,
                  ``,
                  `/** Apply ui_resolve_base_dir() to localized text widgets (layout stays LTR). */`,
                  `void ui_apply_text_direction(void);`
              ]
            : []),
        ``,
        `/** Call once from ui_init() — selects defaultLocale from strings.res. */`,
        `void ui_strings_init(void);`,
        ``,
        `#endif /* UI_STRINGS_H */`,
        ``
    ].join("\n");

    const localeDefs = new Map<string, string>();
    for (const localeId of Object.keys(locales.locales).sort()) {
        const table = locales.locales[localeId] ?? {};
        const listLines = keys
            .map(k => {
                const text = Object.prototype.hasOwnProperty.call(table, k) ? table[k] : k;
                return `    X(${stringKeyToEnumSymbol(k)}, "${escapeCString(text)}")`;
            })
            .join(" \\\n");
        const base = localeToDefBasename(localeId);
        const listMacro = localeToStringListMacro(localeId);
        localeDefs.set(
            localeId,
            [
                AUTOGEN_BANNER,
                `#ifndef UI_STRINGS_${base.toUpperCase()}_DEF`,
                `#define UI_STRINGS_${base.toUpperCase()}_DEF`,
                ``,
                `#define ${listMacro} \\`,
                listLines,
                ``,
                `#endif /* UI_STRINGS_${base.toUpperCase()}_DEF */`,
                ``
            ].join("\n")
        );
    }

    const localeIdsSorted = Object.keys(locales.locales).sort();
    const defaultBase = localeToDefBasename(defaultLocale);

    const tableBlocks = localeIdsSorted
        .map(loc => {
            const base = localeToDefBasename(loc);
            const listMacro = localeToStringListMacro(loc);
            return [
                `#include "ui_strings_${base}.def"`,
                `static const char *const ui_strings_table_${base}[UI_STR_COUNT] = {`,
                `#define X(id, text) text,`,
                `    ${listMacro}`,
                `#undef X`,
                `};`
            ].join("\n");
        })
        .join("\n\n");

    const localeEntries = localeIdsSorted
        .map(loc => {
            const base = localeToDefBasename(loc);
            return `    { "${escapeCString(loc)}", ui_strings_table_${base} }`;
        })
        .join(",\n");

    const localizedWidgets = collectLocalizedWidgets(project);
    const refreshLines = localizedWidgets.map(w => emitRefreshLine(w, needsRtl));
    const refreshBody =
        refreshLines.length > 0
            ? refreshLines.join("\n")
            : "    /* no localized widgets */";
    const buttonHelper =
        localizedWidgets.some(b => b.kind === "button") ? [buildButtonLabelHelper(needsRtl)] : [];
    const localizedStyleHelper = needsRtl ? [LOCALIZED_LABEL_STYLE_HELPER] : [];

    const refreshSource = [
        AUTOGEN_BANNER,
        `/* ui.h pulls in page widget externs used below. */`,
        `#include "ui.h"`,
        `#include "ui_strings.h"`,
        ``,
        ...localizedStyleHelper,
        ...buttonHelper,
        `void ui_refresh_localized_text(void)`,
        `{`,
        refreshBody,
        ...(needsRtl ? [`    lv_obj_invalidate(lv_screen_active());`] : []),
        `}`,
        ``
    ].join("\n");

    const directionLines = needsRtl ? emitDirectionHelpers(project, locales) : [];

    const setLocaleTail = [`            lv_async_call(ui_locale_apply_async_cb, NULL);`];

    const localeApplyAsyncFn = [
        `static void ui_locale_apply_async_cb(void *user_data)`,
        `{`,
        `    (void)user_data;`,
        `    ui_refresh_localized_text();`,
        `}`,
        ``
    ];

    const source = [
        AUTOGEN_BANNER,
        `#include "ui_strings.h"`,
        `#include "ui.h"`,
        `#include <string.h>`,
        ``,
        ...directionLines,
        ...localeApplyAsyncFn,
        tableBlocks,
        ``,
        `typedef struct {`,
        `    const char *id;`,
        `    const char *const *table;`,
        `} ui_locale_entry_t;`,
        ``,
        `static const ui_locale_entry_t ui_locale_entries[] = {`,
        localeEntries,
        `};`,
        ``,
        `static const char *const *ui_strings_active = ui_strings_table_${defaultBase};`,
        `static const char *ui_active_locale_id = "${escapeCString(defaultLocale)}";`,
        ``,
        `void ui_strings_init(void)`,
        `{`,
        `    /* Default locale table is selected by static initializers; do not refresh here —`,
        `     * widgets are not created until after ui_strings_init() returns from ui_init(). */`,
        `}`,
        ``,
        `void ui_set_locale(const char *locale_id)`,
        `{`,
        `    if (!locale_id) {`,
        `        return;`,
        `    }`,
        `    for (unsigned i = 0; i < sizeof(ui_locale_entries) / sizeof(ui_locale_entries[0]); i++) {`,
        `        if (strcmp(locale_id, ui_locale_entries[i].id) == 0) {`,
        `            ui_strings_active = ui_locale_entries[i].table;`,
        `            ui_active_locale_id = ui_locale_entries[i].id;`,
        ...setLocaleTail,
        `            return;`,
        `        }`,
        `    }`,
        `}`,
        ``,
        `const char *ui_get_active_locale(void)`,
        `{`,
        `    return ui_active_locale_id;`,
        `}`,
        ``,
        `const char *ui_get_string(ui_string_id_t id)`,
        `{`,
        `    if (!ui_strings_active || (unsigned)id >= (unsigned)UI_STR_COUNT) {`,
        `        return "";`,
        `    }`,
        `    return ui_strings_active[id];`,
        `}`,
        ``
    ].join("\n");

    return {
        keys,
        localeIds: Object.keys(locales.locales).sort(),
        defaultLocale,
        idsHeader,
        header,
        source,
        refreshSource,
        localeDefs
    };
}

/** Emit lv_label_set_text argument for widget copy (literal, binding placeholder, or ui_get_string). */
export function emitWidgetTextExpr(text: WidgetTextValue, stringsApi: boolean): string {
    if (typeof text === "string") {
        if (/\{\{/.test(text)) {
            return `""`;
        }
        return `"${escapeCString(text)}"`;
    }
    if (stringsApi) {
        return `ui_get_string(${stringKeyToEnumSymbol(text.ref)})`;
    }
    return `"${escapeCString(text.ref)}"`;
}

export function isWidgetTextResourceRef(text: WidgetTextValue | undefined): text is { ref: string } {
    return isStringResourceRef(text);
}
