import type { EmbfProject, StyleDef, StyleProps } from "../types/embf";
import { lvglIncludeDirective } from "./lvglInclude";
import { hexToLvColor } from "./styleGen";

const AUTOGEN_BANNER = `/*
 * AUTO-GENERATED by EmbeddedFlow — do not edit manually.
 * To regenerate: VSCode → Command Palette → "EmbeddedFlow: Generate C Code"
 */
`;

export function styleVarName(id: string): string {
    const safe = id.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^_+|_+$/g, "");
    return `ui_style_${safe || "style"}`;
}

/** Project-aware emit of named-style initialisation lines (one `lv_style_init` + setters per def). */
function emitStyleInitBody(defs: StyleDef[]): string[] {
    const lines: string[] = [];
    for (const def of defs) {
        const sv = styleVarName(def.id);
        lines.push(`    /* ${def.id}${def.name ? ` — ${def.name}` : ""} */`);
        lines.push(`    lv_style_init(&${sv});`);
        lines.push(...emitStylePropertySetters(sv, def.props));
        lines.push("");
    }
    return lines;
}

function emitStylePropertySetters(sv: string, props: StyleProps): string[] {
    const lines: string[] = [];
    const set = (fn: string, ...args: string[]) =>
        `    lv_style_set_${fn}(&${sv}, ${args.join(", ")});`;

    if (props.bgColor !== undefined) {
        lines.push(set("bg_color", hexToLvColor(props.bgColor)));
        lines.push(set("bg_opa", "LV_OPA_COVER"));
    }
    if (props.bgOpacity !== undefined) {
        lines.push(set("bg_opa", String(Math.round(props.bgOpacity))));
    }
    if (props.borderColor !== undefined) {
        lines.push(set("border_color", hexToLvColor(props.borderColor)));
    }
    if (props.borderWidth !== undefined) {
        lines.push(set("border_width", String(props.borderWidth)));
    }
    if (props.borderRadius !== undefined) {
        lines.push(set("radius", String(props.borderRadius)));
    }
    if (props.textColor !== undefined) {
        lines.push(set("text_color", hexToLvColor(props.textColor)));
    }
    if (props.align !== undefined) {
        const map: Record<string, string> = {
            left: "LV_TEXT_ALIGN_LEFT",
            center: "LV_TEXT_ALIGN_CENTER",
            right: "LV_TEXT_ALIGN_RIGHT"
        };
        lines.push(set("text_align", map[props.align] ?? "LV_TEXT_ALIGN_LEFT"));
    }
    if (props.padding !== undefined) {
        if (typeof props.padding === "number") {
            lines.push(set("pad_all", String(props.padding)));
        } else if (Array.isArray(props.padding)) {
            const p = props.padding as number[];
            if (p.length === 2) {
                lines.push(set("pad_top", String(p[0])));
                lines.push(set("pad_bottom", String(p[0])));
                lines.push(set("pad_left", String(p[1])));
                lines.push(set("pad_right", String(p[1])));
            } else if (p.length === 4) {
                lines.push(set("pad_top", String(p[0])));
                lines.push(set("pad_right", String(p[1])));
                lines.push(set("pad_bottom", String(p[2])));
                lines.push(set("pad_left", String(p[3])));
            }
        }
    }
    return lines;
}

/** Header for shared named styles; `null` when project has no `styles[]`. */
export function generateStylesHeader(project: EmbfProject): string | null {
    const defs = project.styles ?? [];
    if (defs.length === 0) {
        return null;
    }
    const externs = defs.map(d => `extern lv_style_t ${styleVarName(d.id)};`);

    return [
        AUTOGEN_BANNER,
        `#ifndef UI_STYLES_H`,
        `#define UI_STYLES_H`,
        ``,
        `#ifdef __cplusplus`,
        `extern "C" {`,
        `#endif`,
        ``,
        lvglIncludeDirective(project),
        ``,
        `/* Named lv_style_t objects defined in ui_styles.c. */`,
        ...externs,
        ``,
        `/** Initialise every named style. Call once from ui_init() before screen creation. */`,
        `void ui_styles_init(void);`,
        ``,
        `#ifdef __cplusplus`,
        `} /* extern "C" */`,
        `#endif`,
        ``,
        `#endif /* UI_STYLES_H */`,
        ``
    ].join("\n");
}

/** Source file (definitions + init); `null` when no styles. */
export function generateStylesSource(project: EmbfProject): string | null {
    const defs = project.styles ?? [];
    if (defs.length === 0) {
        return null;
    }
    const definitions = defs.map(d => `lv_style_t ${styleVarName(d.id)};`);
    const body = emitStyleInitBody(defs);

    return [
        AUTOGEN_BANNER,
        `#include "ui_styles.h"`,
        ``,
        ...definitions,
        ``,
        `void ui_styles_init(void)`,
        `{`,
        ...body,
        `}`,
        ``
    ].join("\n");
}
